from enum import IntFlag
from BaseClasses import ItemClassification as IC
from BaseClasses import Item


class ItemData:
    def __init__(self, item_id, classification, groups):
        self.classification = classification
        self.id = item_id
        self.groups = groups


class MonsterSanctuaryItem(Item):
    game: str = "Monster Sanctuary"

    def __init__(self, name, data: ItemData, player: int = None):
        super(MonsterSanctuaryItem, self).__init__(
            name,
            data.classification,
            data.id,
            player)

item_table = {
    # Key Items
    "Sanctuary Token": ItemData(IC.progression, 1, ["Key Item"]),
    "Double Jump Boots": ItemData(IC.progression, 2, ["Key Item", "Unique"]),
    "Warm Underwear": ItemData(IC.progression, 3, ["Key Item", "Unique"]),
    "Runestone Shard": ItemData(IC.progression, 4, ["Key Item", "Unique"]),
    "Key of Power": ItemData(IC.progression, 5, ["Key Item", "Unique"]),
    "Ahrimaaya": ItemData(IC.progression, 6, ["Key Item", "Unique"]),
    "Blob Key": ItemData(IC.progression, 7, ["Key Item", "Unique"]),
    "Mozzie": ItemData(IC.progression, 8, ["Key Item", "Unique"]),
    "Rare Seashell": ItemData(IC.progression, 9, ["Key Item"]),
    "Celestial Feather": ItemData(IC.progression, 10, ["Key Item"]),
    "Mountain Path Key": ItemData(IC.progression, 11, ["Key Item", "Area Key"]),
    "Blue Caves Key": ItemData(IC.progression, 12, ["Key Item", "Area Key"]),
    "Stronghold Dungeon Key": ItemData(IC.progression, 13, ["Key Item", "Area Key"]),
    "Ancient Woods Key": ItemData(IC.progression, 14, ["Key Item", "Area Key"]),
    "Magma Chamber Key": ItemData(IC.progression, 15, ["Key Item", "Area Key"]),
    "Mystical Workshop Key": ItemData(IC.progression, 16, ["Key Item", "Area Key"]),
    "Underworld Key": ItemData(IC.progression, 17, ["Key Item", "Area Key"]),

    # Crafting Materials
    "Copper": ItemData(IC.filler, 50, ["Crafting Materials", "Tier 1"]),
    "Iron": ItemData(IC.filler, 51, ["Crafting Materials", "Tier 2"]),
    "Bronze": ItemData(IC.filler, 52, ["Crafting Materials", "Tier 2"]),
    "Steel": ItemData(IC.filler, 53, ["Crafting Materials", "Tier 4"]),
    "Silver": ItemData(IC.filler, 54, ["Crafting Materials", "Tier 4"]),
    "Gold": ItemData(IC.filler, 55, ["Crafting Materials", "Tier 5"]),
    "Cotton": ItemData(IC.filler, 50, ["Crafting Materials", "Tier 1"]),
    "Wool": ItemData(IC.filler, 51, ["Crafting Materials", "Tier 2"]),
    "Leather": ItemData(IC.filler, 52, ["Crafting Materials", "Tier 3"]),
    # Raw Hide unlocks a check, so it has to be progression
    "Raw Hide": ItemData(IC.progression, 53, ["Crafting Materials", "Tier 3"]),
    "Silk": ItemData(IC.filler, 54, ["Crafting Materials", "Tier 4"]),
    "Linen": ItemData(IC.filler, 55, ["Crafting Materials", "Tier 5"]),
    "Red Gem": ItemData(IC.filler, 56, ["Crafting Materials", "Tier 1"]),
    "Green Gem": ItemData(IC.filler, 57, ["Crafting Materials", "Tier 1"]),
    "Blue Gem": ItemData(IC.filler, 58, ["Crafting Materials", "Tier 1"]),
    "Crimson Gem": ItemData(IC.filler, 59, ["Crafting Materials", "Tier 3"]),
    "Verdant Gem": ItemData(IC.filler, 60, ["Crafting Materials", "Tier 3"]),
    "Azure Gem": ItemData(IC.filler, 61, ["Crafting Materials", "Tier 3"]),
    "Ruby": ItemData(IC.filler, 62, ["Crafting Materials", "Tier 5"]),
    "Emerald": ItemData(IC.filler, 63, ["Crafting Materials", "Tier 5"]),
    "Sapphire": ItemData(IC.filler, 64, ["Crafting Materials", "Tier 5"]),

    # Consumables
    # this might need to be adjusted, because teleporting to keeper stronghold early might break things
    "Crystal Shard": ItemData(IC.filler, 80, ["Consumable"]),
    "Monster Bell": ItemData(IC.filler, 81, ["Consumable"]),
    "Skill Resetter": ItemData(IC.filler, 82, ["Consumable"]),
    "Skill Potion": ItemData(IC.useful, 83, ["Consumable"]),
    "Level Badge": ItemData(IC.useful, 84, ["Consumable"]),
    # the below tiers might be off and need balancing
    "Level Badge 42": ItemData(IC.useful, 85, ["Consumable", "Tier 5"]),
    "Shift Stone": ItemData(IC.useful, 86, ["Consumable", "Tier 3"]),
    "Switch Stone": ItemData(IC.useful, 87, ["Consumable", "Tier 3"]),
    "Clear Stone": ItemData(IC.filler, 88, ["Consumable", "Tier 3"]),
    "Craft Box": ItemData(IC.filler, 89, ["Consumable"]),
    "Reward Box Lvl 1": ItemData(IC.useful, 90, ["Consumable", "Tier 1"]),
    "Reward Box Lvl 2": ItemData(IC.useful, 91, ["Consumable", "Tier 2"]),
    "Reward Box Lvl 3": ItemData(IC.useful, 92, ["Consumable", "Tier 3"]),
    "Reward Box Lvl 4": ItemData(IC.useful, 93, ["Consumable", "Tier 4"]),
    "Reward Box Lvl 5": ItemData(IC.useful, 94, ["Consumable", "Tier 5"]),
    "Reward Box Lvl X": ItemData(IC.useful, 95, ["Consumable", "Tier 5"]),
    "Small Potion": ItemData(IC.filler, 96, ["Consumable", "Tier 1"]),
    "Potion": ItemData(IC.filler, 97, ["Consumable", "Tier 2"]),
    "Mass Potion": ItemData(IC.useful, 98, ["Consumable", "Tier 3"]),
    "Combo Potion": ItemData(IC.filler, 99, ["Consumable", "Tier 3"]),
    "Big Potion": ItemData(IC.filler, 100, ["Consumable", "Tier 4"]),
    "Mega Potion": ItemData(IC.filler, 101, ["Consumable", "Tier 5"]),
    "Antidote": ItemData(IC.filler, 102, ["Consumable", "Tier 1"]),
    "Mass Antidote": ItemData(IC.filler, 103, ["Consumable", "Tier 2"]),
    "Phoenix Tear": ItemData(IC.filler, 104, ["Consumable"]),
    "Phoenix Serum": ItemData(IC.filler, 105, ["Consumable", "Tier 3"]),
    "Smoke Bomb": ItemData(IC.filler, 105, ["Consumable"]),

    # Foods
    "Walnut": ItemData(IC.filler, 120, ["Food", "Tier 1"]),
    "Hazelnut": ItemData(IC.filler, 121, ["Food", "Tier 2"]),
    "Almond": ItemData(IC.filler, 122, ["Food", "Tier 3"]),
    "Peanut": ItemData(IC.filler, 123, ["Food", "Tier 4"]),
    "Potato": ItemData(IC.filler, 124, ["Food", "Tier 1"]),
    "Corn": ItemData(IC.filler, 125, ["Food", "Tier 2"]),
    "Carrot": ItemData(IC.filler, 126, ["Food", "Tier 3"]),
    "Banana": ItemData(IC.filler, 127, ["Food", "Tier 4"]),
    "Apple": ItemData(IC.filler, 128, ["Food", "Tier 1"]),
    "Pear": ItemData(IC.filler, 129, ["Food", "Tier 2"]),
    "Mango": ItemData(IC.filler, 130, ["Food", "Tier 3"]),
    "Orange": ItemData(IC.filler, 131, ["Food", "Tier 4"]),
    "Berry": ItemData(IC.filler, 132, ["Food", "Tier 1"]),
    "Grapes": ItemData(IC.filler, 133, ["Food", "Tier 2"]),
    "Strawberry": ItemData(IC.filler, 134, ["Food", "Tier 3"]),
    "Raspberry": ItemData(IC.filler, 135, ["Food", "Tier 4"]),
    "Cookie Mushroom": ItemData(IC.filler, 136, ["Food"]),

    # Catalysts
    "Stardust": ItemData(IC.useful, 150, ["Catalyst"]),
    "Cocoon": ItemData(IC.useful, 151, ["Catalyst"]),
    "Shard of Winter": ItemData(IC.useful, 152, ["Catalyst"]),
    "Magical Clay": ItemData(IC.useful, 153, ["Catalyst"]),
    "Sun Stone": ItemData(IC.useful, 154, ["Catalyst"]),
    "Silver Feather": ItemData(IC.useful, 155, ["Catalyst"]),
    "Volcanic Ash": ItemData(IC.useful, 156, ["Catalyst"]),
    "Fire Stone": ItemData(IC.useful, 157, ["Catalyst"]),
    "Ice Stone": ItemData(IC.useful, 158, ["Catalyst"]),
    "Giant Seed": ItemData(IC.useful, 159, ["Catalyst"]),
    "Dark Stone": ItemData(IC.useful, 160, ["Catalyst"]),
    "Majestic Crown": ItemData(IC.useful, 161, ["Catalyst"]),
    "Demonic Pact": ItemData(IC.useful, 162, ["Catalyst"]),
    "Primordial Branchy": ItemData(IC.useful, 163, ["Catalyst"]),
    "Druid Soul": ItemData(IC.useful, 164, ["Catalyst"]),
    "Deep Stone": ItemData(IC.useful, 165, ["Catalyst"]),

    # Basic Weapons
    "Morning Star": ItemData(IC.filler, 180, ["Equipment", "Tier 1"]),
    "Morning Star +1": ItemData(IC.filler, 181, ["Equipment", "Tier 2"]),
    "Morning Star +2": ItemData(IC.filler, 182, ["Equipment", "Tier 3"]),
    "Morning Star +3": ItemData(IC.filler, 183, ["Equipment", "Tier 4"]),
    "Morning Star +4": ItemData(IC.filler, 184, ["Equipment", "Tier 5"]),
    "Morning Star +5": ItemData(IC.filler, 185, ["Equipment", "Tier 5"]),
    "Claws": ItemData(IC.filler, 186, ["Equipment", "Tier 1"]),
    "Claws +1": ItemData(IC.filler, 187, ["Equipment", "Tier 2"]),
    "Claws +2": ItemData(IC.filler, 188, ["Equipment", "Tier 3"]),
    "Claws +3": ItemData(IC.filler, 189, ["Equipment", "Tier 4"]),
    "Claws +4": ItemData(IC.filler, 190, ["Equipment", "Tier 5"]),
    "Claws +5": ItemData(IC.filler, 191, ["Equipment", "Tier 5"]),
    "Katar": ItemData(IC.filler, 191, ["Equipment", "Tier 1"]),
    "Katar +1": ItemData(IC.filler, 192, ["Equipment", "Tier 2"]),
    "Katar +2": ItemData(IC.filler, 193, ["Equipment", "Tier 3"]),
    "Katar +3": ItemData(IC.filler, 194, ["Equipment", "Tier 4"]),
    "Katar +4": ItemData(IC.filler, 195, ["Equipment", "Tier 5"]),
    "Katar +5": ItemData(IC.filler, 196, ["Equipment", "Tier 5"]),
    "Wand": ItemData(IC.filler, 197, ["Equipment", "Tier 1"]),
    "Wand +1": ItemData(IC.filler, 199, ["Equipment", "Tier 2"]),
    "Wand +2": ItemData(IC.filler, 200, ["Equipment", "Tier 3"]),
    "Wand +3": ItemData(IC.filler, 201, ["Equipment", "Tier 4"]),
    "Wand +4": ItemData(IC.filler, 202, ["Equipment", "Tier 5"]),
    "Wand +5": ItemData(IC.filler, 203, ["Equipment", "Tier 5"]),
    "Orb": ItemData(IC.filler, 204, ["Equipment", "Tier 1"]),
    "Orb +1": ItemData(IC.filler, 205, ["Equipment", "Tier 2"]),
    "Orb +2": ItemData(IC.filler, 206, ["Equipment", "Tier 3"]),
    "Orb +3": ItemData(IC.filler, 207, ["Equipment", "Tier 4"]),
    "Orb +4": ItemData(IC.filler, 208, ["Equipment", "Tier 5"]),
    "Orb +5": ItemData(IC.filler, 209, ["Equipment", "Tier 5"]),
    "Staff": ItemData(IC.filler, 210, ["Equipment", "Tier 1"]),
    "Staff +1": ItemData(IC.filler, 211, ["Equipment", "Tier 2"]),
    "Staff +2": ItemData(IC.filler, 212, ["Equipment", "Tier 3"]),
    "Staff +3": ItemData(IC.filler, 213, ["Equipment", "Tier 4"]),
    "Staff +4": ItemData(IC.filler, 214, ["Equipment", "Tier 5"]),
    "Staff +5": ItemData(IC.filler, 215, ["Equipment", "Tier 5"]),
    "Cestus": ItemData(IC.filler, 216, ["Equipment", "Tier 1"]),
    "Cestus +1": ItemData(IC.filler, 217, ["Equipment", "Tier 2"]),
    "Cestus +2": ItemData(IC.filler, 218, ["Equipment", "Tier 3"]),
    "Cestus +3": ItemData(IC.filler, 219, ["Equipment", "Tier 4"]),
    "Cestus +4": ItemData(IC.filler, 220, ["Equipment", "Tier 5"]),
    "Cestus +5": ItemData(IC.filler, 221, ["Equipment", "Tier 5"]),
    "Kunai": ItemData(IC.filler, 222, ["Equipment", "Tier 1"]),
    "Kunai +1": ItemData(IC.filler, 223, ["Equipment", "Tier 2"]),
    "Kunai +2": ItemData(IC.filler, 224, ["Equipment", "Tier 3"]),
    "Kunai +3": ItemData(IC.filler, 225, ["Equipment", "Tier 4"]),
    "Kunai +4": ItemData(IC.filler, 226, ["Equipment", "Tier 5"]),
    "Kunai +5": ItemData(IC.filler, 227, ["Equipment", "Tier 5"]),
    "Shuriken": ItemData(IC.filler, 228, ["Equipment", "Tier 1"]),
    "Shuriken +1": ItemData(IC.filler, 229, ["Equipment", "Tier 2"]),
    "Shuriken +2": ItemData(IC.filler, 230, ["Equipment", "Tier 3"]),
    "Shuriken +3": ItemData(IC.filler, 231, ["Equipment", "Tier 4"]),
    "Shuriken +4": ItemData(IC.filler, 232, ["Equipment", "Tier 5"]),
    "Shuriken +5": ItemData(IC.filler, 233, ["Equipment", "Tier 5"]),

    # Unique Weapons
    "Abyssal Sword": ItemData(IC.filler, 250, ["Equipment", "Tier 1", "Unique"]),
    "Abyssal Sword +1": ItemData(IC.filler, 251, ["Equipment", "Tier 2", "Unique"]),
    "Abyssal Sword +2": ItemData(IC.filler, 252, ["Equipment", "Tier 3", "Unique"]),
    "Abyssal Sword +3": ItemData(IC.filler, 253, ["Equipment", "Tier 4", "Unique"]),
    "Abyssal Sword +4": ItemData(IC.filler, 254, ["Equipment", "Tier 5", "Unique"]),
    "Abyssal Sword +5": ItemData(IC.filler, 255, ["Equipment", "Tier 5", "Unique"]),
    "Bow": ItemData(IC.filler, 256, ["Equipment", "Tier 1", "Unique"]),
    "Bow+1": ItemData(IC.filler, 257, ["Equipment", "Tier 2", "Unique"]),
    "Bow+2": ItemData(IC.filler, 258, ["Equipment", "Tier 3", "Unique"]),
    "Bow+3": ItemData(IC.filler, 259, ["Equipment", "Tier 4", "Unique"]),
    "Bow+4": ItemData(IC.filler, 260, ["Equipment", "Tier 5", "Unique"]),
    "Bow+5": ItemData(IC.filler, 261, ["Equipment", "Tier 5", "Unique"]),
    "Fan": ItemData(IC.filler, 262, ["Equipment", "Tier 1", "Unique"]),
    "Fan +1": ItemData(IC.filler, 263, ["Equipment", "Tier 2", "Unique"]),
    "Fan +2": ItemData(IC.filler, 264, ["Equipment", "Tier 3", "Unique"]),
    "Fan +3": ItemData(IC.filler, 265, ["Equipment", "Tier 4", "Unique"]),
    "Fan +4": ItemData(IC.filler, 266, ["Equipment", "Tier 5", "Unique"]),
    "Fan +5": ItemData(IC.filler, 267, ["Equipment", "Tier 5", "Unique"]),
    "Fishing Rod": ItemData(IC.filler, 268, ["Equipment", "Tier 1", "Unique"]),
    "Fishing Rod +1": ItemData(IC.filler, 269, ["Equipment", "Tier 2", "Unique"]),
    "Fishing Rod +2": ItemData(IC.filler, 270, ["Equipment", "Tier 3", "Unique"]),
    "Fishing Rod +3": ItemData(IC.filler, 271, ["Equipment", "Tier 4", "Unique"]),
    "Fishing Rod +4": ItemData(IC.filler, 272, ["Equipment", "Tier 5", "Unique"]),
    "Fishing Rod +5": ItemData(IC.filler, 273, ["Equipment", "Tier 5", "Unique"]),
    "Hammer": ItemData(IC.filler, 274, ["Equipment", "Tier 1", "Unique"]),
    "Hammer +1": ItemData(IC.filler, 275, ["Equipment", "Tier 2", "Unique"]),
    "Hammer +2": ItemData(IC.filler, 276, ["Equipment", "Tier 3", "Unique"]),
    "Hammer +3": ItemData(IC.filler, 277, ["Equipment", "Tier 4", "Unique"]),
    "Hammer +4": ItemData(IC.filler, 278, ["Equipment", "Tier 5", "Unique"]),
    "Hammer +5": ItemData(IC.filler, 279, ["Equipment", "Tier 5", "Unique"]),
    "Harp": ItemData(IC.filler, 280, ["Equipment", "Tier 1", "Unique"]),
    "Harp +1": ItemData(IC.filler, 281, ["Equipment", "Tier 2", "Unique"]),
    "Harp +2": ItemData(IC.filler, 282, ["Equipment", "Tier 3", "Unique"]),
    "Harp +3": ItemData(IC.filler, 283, ["Equipment", "Tier 4", "Unique"]),
    "Harp +4": ItemData(IC.filler, 284, ["Equipment", "Tier 5", "Unique"]),
    "Harp +5": ItemData(IC.filler, 285, ["Equipment", "Tier 5", "Unique"]),
    "Heavy Mace": ItemData(IC.filler, 286, ["Equipment", "Tier 1", "Unique"]),
    "Heavy Mace +1": ItemData(IC.filler, 287, ["Equipment", "Tier 2", "Unique"]),
    "Heavy Mace +2": ItemData(IC.filler, 288, ["Equipment", "Tier 3", "Unique"]),
    "Heavy Mace +3": ItemData(IC.filler, 289, ["Equipment", "Tier 4", "Unique"]),
    "Heavy Mace +4": ItemData(IC.filler, 290, ["Equipment", "Tier 5", "Unique"]),
    "Heavy Mace +5": ItemData(IC.filler, 291, ["Equipment", "Tier 5", "Unique"]),
    "Hexing Rod": ItemData(IC.filler, 292, ["Equipment", "Tier 1", "Unique"]),
    "Hexing Rod +1": ItemData(IC.filler, 293, ["Equipment", "Tier 2", "Unique"]),
    "Hexing Rod +2": ItemData(IC.filler, 294, ["Equipment", "Tier 3", "Unique"]),
    "Hexing Rod +3": ItemData(IC.filler, 295, ["Equipment", "Tier 4", "Unique"]),
    "Hexing Rod +4": ItemData(IC.filler, 296, ["Equipment", "Tier 5", "Unique"]),
    "Hexing Rod +5": ItemData(IC.filler, 297, ["Equipment", "Tier 5", "Unique"]),
    "Katana": ItemData(IC.filler, 298, ["Equipment", "Tier 1", "Unique"]),
    "Katana +1": ItemData(IC.filler, 299, ["Equipment", "Tier 2", "Unique"]),
    "Katana +2": ItemData(IC.filler, 300, ["Equipment", "Tier 3", "Unique"]),
    "Katana +3": ItemData(IC.filler, 301, ["Equipment", "Tier 4", "Unique"]),
    "Katana +4": ItemData(IC.filler, 302, ["Equipment", "Tier 5", "Unique"]),
    "Katana +5": ItemData(IC.filler, 303, ["Equipment", "Tier 5", "Unique"]),
    "Large Shield": ItemData(IC.filler, 304, ["Equipment", "Tier 1", "Unique"]),
    "Large Shield +1": ItemData(IC.filler, 305, ["Equipment", "Tier 2", "Unique"]),
    "Large Shield +2": ItemData(IC.filler, 306, ["Equipment", "Tier 3", "Unique"]),
    "Large Shield +3": ItemData(IC.filler, 307, ["Equipment", "Tier 4", "Unique"]),
    "Large Shield +4": ItemData(IC.filler, 308, ["Equipment", "Tier 5", "Unique"]),
    "Large Shield +5": ItemData(IC.filler, 309, ["Equipment", "Tier 5", "Unique"]),
    "Mandolin ": ItemData(IC.filler, 310, ["Equipment", "Tier 1", "Unique"]),
    "Mandolin +1": ItemData(IC.filler, 311, ["Equipment", "Tier 2", "Unique"]),
    "Mandolin +2": ItemData(IC.filler, 312, ["Equipment", "Tier 3", "Unique"]),
    "Mandolin +3": ItemData(IC.filler, 313, ["Equipment", "Tier 4", "Unique"]),
    "Mandolin +4": ItemData(IC.filler, 314, ["Equipment", "Tier 5", "Unique"]),
    "Mandolin +5": ItemData(IC.filler, 315, ["Equipment", "Tier 5", "Unique"]),
    "Moon Sword": ItemData(IC.filler, 316, ["Equipment", "Tier 1", "Unique"]),
    "Moon Sword +1": ItemData(IC.filler, 317, ["Equipment", "Tier 2", "Unique"]),
    "Moon Sword +2": ItemData(IC.filler, 318, ["Equipment", "Tier 3", "Unique"]),
    "Moon Sword +3": ItemData(IC.filler, 319, ["Equipment", "Tier 4", "Unique"]),
    "Moon Sword +4": ItemData(IC.filler, 320, ["Equipment", "Tier 5", "Unique"]),
    "Moon Sword +5": ItemData(IC.filler, 321, ["Equipment", "Tier 5", "Unique"]),
    "Pirate Hook": ItemData(IC.filler, 322, ["Equipment", "Tier 1", "Unique"]),
    "Pirate Hook +1": ItemData(IC.filler, 323, ["Equipment", "Tier 2", "Unique"]),
    "Pirate Hook +2": ItemData(IC.filler, 324, ["Equipment", "Tier 3", "Unique"]),
    "Pirate Hook +3": ItemData(IC.filler, 325, ["Equipment", "Tier 4", "Unique"]),
    "Pirate Hook +4": ItemData(IC.filler, 326, ["Equipment", "Tier 5", "Unique"]),
    "Pirate Hook +5": ItemData(IC.filler, 327, ["Equipment", "Tier 5", "Unique"]),
    "Purifying Mace": ItemData(IC.filler, 328, ["Equipment", "Tier 1", "Unique"]),
    "Purifying Mace +1": ItemData(IC.filler, 329, ["Equipment", "Tier 2", "Unique"]),
    "Purifying Mace +2": ItemData(IC.filler, 330, ["Equipment", "Tier 3", "Unique"]),
    "Purifying Mace +3": ItemData(IC.filler, 331, ["Equipment", "Tier 4", "Unique"]),
    "Purifying Mace +4": ItemData(IC.filler, 332, ["Equipment", "Tier 5", "Unique"]),
    "Purifying Mace +5": ItemData(IC.filler, 333, ["Equipment", "Tier 5", "Unique"]),
    "Restoring Wand": ItemData(IC.filler, 334, ["Equipment", "Tier 1", "Unique"]),
    "Restoring Wand +1": ItemData(IC.filler, 335, ["Equipment", "Tier 2", "Unique"]),
    "Restoring Wand +2": ItemData(IC.filler, 336, ["Equipment", "Tier 3", "Unique"]),
    "Restoring Wand +3": ItemData(IC.filler, 337, ["Equipment", "Tier 4", "Unique"]),
    "Restoring Wand +4": ItemData(IC.filler, 338, ["Equipment", "Tier 5", "Unique"]),
    "Restoring Wand +5": ItemData(IC.filler, 339, ["Equipment", "Tier 5", "Unique"]),
    "Scepter": ItemData(IC.filler, 340, ["Equipment", "Tier 1", "Unique"]),
    "Scepter +1": ItemData(IC.filler, 341, ["Equipment", "Tier 2", "Unique"]),
    "Scepter +2": ItemData(IC.filler, 342, ["Equipment", "Tier 3", "Unique"]),
    "Scepter +3": ItemData(IC.filler, 343, ["Equipment", "Tier 4", "Unique"]),
    "Scepter +4": ItemData(IC.filler, 344, ["Equipment", "Tier 5", "Unique"]),
    "Scepter +5": ItemData(IC.filler, 345, ["Equipment", "Tier 5", "Unique"]),
    "Scythe": ItemData(IC.filler, 346, ["Equipment", "Tier 1", "Unique"]),
    "Scythe +1": ItemData(IC.filler, 347, ["Equipment", "Tier 2", "Unique"]),
    "Scythe +2": ItemData(IC.filler, 348, ["Equipment", "Tier 3", "Unique"]),
    "Scythe +3": ItemData(IC.filler, 349, ["Equipment", "Tier 4", "Unique"]),
    "Scythe +4": ItemData(IC.filler, 350, ["Equipment", "Tier 5", "Unique"]),
    "Scythe +5": ItemData(IC.filler, 351, ["Equipment", "Tier 5", "Unique"]),
    "Summoned Sword": ItemData(IC.filler, 352, ["Equipment", "Tier 1", "Unique"]),
    "Summoned Sword +1": ItemData(IC.filler, 353, ["Equipment", "Tier 2", "Unique"]),
    "Summoned Sword +2": ItemData(IC.filler, 354, ["Equipment", "Tier 3", "Unique"]),
    "Summoned Sword +3": ItemData(IC.filler, 355, ["Equipment", "Tier 4", "Unique"]),
    "Summoned Sword +4": ItemData(IC.filler, 356, ["Equipment", "Tier 5", "Unique"]),
    "Summoned Sword +5": ItemData(IC.filler, 357, ["Equipment", "Tier 5", "Unique"]),
    "Swallow": ItemData(IC.filler, 358, ["Equipment", "Tier 1", "Unique"]),
    "Swallow +1": ItemData(IC.filler, 359, ["Equipment", "Tier 2", "Unique"]),
    "Swallow +2": ItemData(IC.filler, 360, ["Equipment", "Tier 3", "Unique"]),
    "Swallow +3": ItemData(IC.filler, 361, ["Equipment", "Tier 4", "Unique"]),
    "Swallow +4": ItemData(IC.filler, 362, ["Equipment", "Tier 5", "Unique"]),
    "Swallow +5": ItemData(IC.filler, 363, ["Equipment", "Tier 5", "Unique"]),
    "Thorn Tendril": ItemData(IC.filler, 364, ["Equipment", "Tier 1", "Unique"]),
    "Thorn Tendril +1": ItemData(IC.filler, 365, ["Equipment", "Tier 2", "Unique"]),
    "Thorn Tendril +2": ItemData(IC.filler, 366, ["Equipment", "Tier 3", "Unique"]),
    "Thorn Tendril +3": ItemData(IC.filler, 367, ["Equipment", "Tier 4", "Unique"]),
    "Thorn Tendril +4": ItemData(IC.filler, 368, ["Equipment", "Tier 5", "Unique"]),
    "Thorn Tendril +5": ItemData(IC.filler, 369, ["Equipment", "Tier 5", "Unique"]),
    "Torch": ItemData(IC.filler, 370, ["Equipment", "Tier 1", "Unique"]),
    "Torch +1": ItemData(IC.filler, 371, ["Equipment", "Tier 2", "Unique"]),
    "Torch +2": ItemData(IC.filler, 372, ["Equipment", "Tier 3", "Unique"]),
    "Torch +3": ItemData(IC.filler, 373, ["Equipment", "Tier 4", "Unique"]),
    "Torch +4": ItemData(IC.filler, 374, ["Equipment", "Tier 5", "Unique"]),
    "Torch +5": ItemData(IC.filler, 375, ["Equipment", "Tier 5", "Unique"]),
    "Trident": ItemData(IC.filler, 376, ["Equipment", "Tier 1", "Unique"]),
    "Trident +1": ItemData(IC.filler, 377, ["Equipment", "Tier 2", "Unique"]),
    "Trident +2": ItemData(IC.filler, 378, ["Equipment", "Tier 3", "Unique"]),
    "Trident +3": ItemData(IC.filler, 379, ["Equipment", "Tier 4", "Unique"]),
    "Trident +4": ItemData(IC.filler, 380, ["Equipment", "Tier 5", "Unique"]),
    "Trident +5": ItemData(IC.filler, 381, ["Equipment", "Tier 5", "Unique"]),
    "Warhorn": ItemData(IC.filler, 382, ["Equipment", "Tier 1", "Unique"]),
    "Warhorn +1": ItemData(IC.filler, 383, ["Equipment", "Tier 2", "Unique"]),
    "Warhorn +2": ItemData(IC.filler, 384, ["Equipment", "Tier 3", "Unique"]),
    "Warhorn +3": ItemData(IC.filler, 385, ["Equipment", "Tier 4", "Unique"]),
    "Warhorn +4": ItemData(IC.filler, 386, ["Equipment", "Tier 5", "Unique"]),
    "Warhorn +5": ItemData(IC.filler, 387, ["Equipment", "Tier 5", "Unique"]),

    # Relic Weapons
    "Arch Bow": ItemData(IC.filler, 400, ["Equipment", "Tier 1", "Unique"]),
    "Arch Bow +1": ItemData(IC.filler, 401, ["Equipment", "Tier 2", "Unique"]),
    "Arch Bow +2": ItemData(IC.filler, 402, ["Equipment", "Tier 3", "Unique"]),
    "Arch Bow +3": ItemData(IC.filler, 403, ["Equipment", "Tier 4", "Unique"]),
    "Arch Bow +4": ItemData(IC.filler, 404, ["Equipment", "Tier 5", "Unique"]),
    "Arch Bow +5": ItemData(IC.filler, 405, ["Equipment", "Tier 5", "Unique"]),
    "Assisting Bow": ItemData(IC.filler, 406, ["Equipment", "Tier 1", "Unique"]),
    "Assisting Bow +1": ItemData(IC.filler, 407, ["Equipment", "Tier 2", "Unique"]),
    "Assisting Bow +2": ItemData(IC.filler, 408, ["Equipment", "Tier 3", "Unique"]),
    "Assisting Bow +3": ItemData(IC.filler, 409, ["Equipment", "Tier 4", "Unique"]),
    "Assisting Bow +4": ItemData(IC.filler, 410, ["Equipment", "Tier 5", "Unique"]),
    "Assisting Bow +5": ItemData(IC.filler, 411, ["Equipment", "Tier 5", "Unique"]),
    "Droid Sphere": ItemData(IC.filler, 412, ["Equipment", "Tier 1", "Unique"]),
    "Droid Sphere +1": ItemData(IC.filler, 413, ["Equipment", "Tier 2", "Unique"]),
    "Droid Sphere +2": ItemData(IC.filler, 414, ["Equipment", "Tier 3", "Unique"]),
    "Droid Sphere +3": ItemData(IC.filler, 415, ["Equipment", "Tier 4", "Unique"]),
    "Droid Sphere +4": ItemData(IC.filler, 416, ["Equipment", "Tier 5", "Unique"]),
    "Droid Sphere +5": ItemData(IC.filler, 417, ["Equipment", "Tier 5", "Unique"]),
    "Eclipse Sword": ItemData(IC.filler, 418, ["Equipment", "Tier 1", "Unique"]),
    "Eclipse Sword +1": ItemData(IC.filler, 419, ["Equipment", "Tier 2", "Unique"]),
    "Eclipse Sword +2": ItemData(IC.filler, 420, ["Equipment", "Tier 3", "Unique"]),
    "Eclipse Sword +3": ItemData(IC.filler, 421, ["Equipment", "Tier 4", "Unique"]),
    "Eclipse Sword +4": ItemData(IC.filler, 422, ["Equipment", "Tier 5", "Unique"]),
    "Eclipse Sword +5": ItemData(IC.filler, 423, ["Equipment", "Tier 5", "Unique"]),
    "Fishing Pole": ItemData(IC.filler, 424, ["Equipment", "Tier 1", "Unique"]),
    "Fishing Pole +1": ItemData(IC.filler, 425, ["Equipment", "Tier 2", "Unique"]),
    "Fishing Pole +2": ItemData(IC.filler, 426, ["Equipment", "Tier 3", "Unique"]),
    "Fishing Pole +3": ItemData(IC.filler, 427, ["Equipment", "Tier 4", "Unique"]),
    "Fishing Pole +4": ItemData(IC.filler, 428, ["Equipment", "Tier 5", "Unique"]),
    "Fishing Pole +5": ItemData(IC.filler, 429, ["Equipment", "Tier 5", "Unique"]),
    "Grim Ripper": ItemData(IC.filler, 430, ["Equipment", "Tier 1", "Unique"]),
    "Grim Ripper +1": ItemData(IC.filler, 431, ["Equipment", "Tier 2", "Unique"]),
    "Grim Ripper +2": ItemData(IC.filler, 432, ["Equipment", "Tier 3", "Unique"]),
    "Grim Ripper +3": ItemData(IC.filler, 433, ["Equipment", "Tier 4", "Unique"]),
    "Grim Ripper +4": ItemData(IC.filler, 434, ["Equipment", "Tier 5", "Unique"]),
    "Grim Ripper +5": ItemData(IC.filler, 435, ["Equipment", "Tier 5", "Unique"]),
    "Omni Sword": ItemData(IC.filler, 436, ["Equipment", "Tier 1", "Unique"]),
    "Omni Sword +1": ItemData(IC.filler, 437, ["Equipment", "Tier 2", "Unique"]),
    "Omni Sword +2": ItemData(IC.filler, 438, ["Equipment", "Tier 3", "Unique"]),
    "Omni Sword +3": ItemData(IC.filler, 439, ["Equipment", "Tier 4", "Unique"]),
    "Omni Sword +4": ItemData(IC.filler, 440, ["Equipment", "Tier 5", "Unique"]),
    "Omni Sword +5": ItemData(IC.filler, 441, ["Equipment", "Tier 5", "Unique"]),
    "One Punch Fist": ItemData(IC.filler, 442, ["Equipment", "Tier 1", "Unique"]),
    "One Punch Fist +1": ItemData(IC.filler, 443, ["Equipment", "Tier 2", "Unique"]),
    "One Punch Fist +2": ItemData(IC.filler, 444, ["Equipment", "Tier 3", "Unique"]),
    "One Punch Fist +3": ItemData(IC.filler, 445, ["Equipment", "Tier 4", "Unique"]),
    "One Punch Fist +4": ItemData(IC.filler, 446, ["Equipment", "Tier 5", "Unique"]),
    "One Punch Fist +5": ItemData(IC.filler, 447, ["Equipment", "Tier 5", "Unique"]),
    "Projectile Sphere": ItemData(IC.filler, 448, ["Equipment", "Tier 1", "Unique"]),
    "Projectile Sphere +1": ItemData(IC.filler, 449, ["Equipment", "Tier 2", "Unique"]),
    "Projectile Sphere +2": ItemData(IC.filler, 450, ["Equipment", "Tier 3", "Unique"]),
    "Projectile Sphere +3": ItemData(IC.filler, 451, ["Equipment", "Tier 4", "Unique"]),
    "Projectile Sphere +4": ItemData(IC.filler, 452, ["Equipment", "Tier 5", "Unique"]),
    "Projectile Sphere +5": ItemData(IC.filler, 453, ["Equipment", "Tier 5", "Unique"]),
    "Staff of Doom": ItemData(IC.filler, 454, ["Equipment", "Tier 1", "Unique"]),
    "Staff of Doom +1": ItemData(IC.filler, 455, ["Equipment", "Tier 2", "Unique"]),
    "Staff of Doom +2": ItemData(IC.filler, 456, ["Equipment", "Tier 3", "Unique"]),
    "Staff of Doom +3": ItemData(IC.filler, 457, ["Equipment", "Tier 4", "Unique"]),
    "Staff of Doom +4": ItemData(IC.filler, 458, ["Equipment", "Tier 5", "Unique"]),
    "Staff of Doom +5": ItemData(IC.filler, 459, ["Equipment", "Tier 5", "Unique"]),
    "Tiny Pin": ItemData(IC.filler, 460, ["Equipment", "Tier 1", "Unique"]),
    "Tiny Pin +1": ItemData(IC.filler, 461, ["Equipment", "Tier 2", "Unique"]),
    "Tiny Pin +2": ItemData(IC.filler, 462, ["Equipment", "Tier 3", "Unique"]),
    "Tiny Pin +3": ItemData(IC.filler, 463, ["Equipment", "Tier 4", "Unique"]),
    "Tiny Pin +4": ItemData(IC.filler, 464, ["Equipment", "Tier 5", "Unique"]),
    "Tiny Pin +5": ItemData(IC.filler, 465, ["Equipment", "Tier 5", "Unique"]),

    # Basic Accessories
    "Shell": ItemData(IC.filler, 500, ["Equipment", "Tier 1"]),
    "Shell +1": ItemData(IC.filler, 501, ["Equipment", "Tier 2"]),
    "Shell +2": ItemData(IC.filler, 502, ["Equipment", "Tier 3", ]),
    "Shell +3": ItemData(IC.filler, 503, ["Equipment", "Tier 4", ]),
    "Shell +4": ItemData(IC.filler, 504, ["Equipment", "Tier 5", ]),
    "Shell +5": ItemData(IC.filler, 505, ["Equipment", "Tier 5", ]),
    "Vital Ring": ItemData(IC.filler, 506, ["Equipment", "Tier 1"]),
    "Vital Ring +1": ItemData(IC.filler, 507, ["Equipment", "Tier 2"]),
    "Vital Ring +2": ItemData(IC.filler, 508, ["Equipment", "Tier 3"]),
    "Vital Ring +3": ItemData(IC.filler, 509, ["Equipment", "Tier 4"]),
    "Vital Ring +4": ItemData(IC.filler, 510, ["Equipment", "Tier 5"]),
    "Vital Ring +5": ItemData(IC.filler, 511, ["Equipment", "Tier 5"]),
    "Mana Ring": ItemData(IC.filler, 512, ["Equipment", "Tier 1"]),
    "Mana Ring +1": ItemData(IC.filler, 513, ["Equipment", "Tier 2"]),
    "Mana Ring +2": ItemData(IC.filler, 514, ["Equipment", "Tier 3"]),
    "Mana Ring +3": ItemData(IC.filler, 515, ["Equipment", "Tier 4"]),
    "Mana Ring +4": ItemData(IC.filler, 516, ["Equipment", "Tier 5"]),
    "Mana Ring +5": ItemData(IC.filler, 517, ["Equipment", "Tier 5"]),
    "Sustain Ring": ItemData(IC.filler, 518, ["Equipment", "Tier 1"]),
    "Sustain Ring +1": ItemData(IC.filler, 519, ["Equipment", "Tier 2"]),
    "Sustain Ring +2": ItemData(IC.filler, 520, ["Equipment", "Tier 3"]),
    "Sustain Ring +3": ItemData(IC.filler, 521, ["Equipment", "Tier 4"]),
    "Sustain Ring +4": ItemData(IC.filler, 522, ["Equipment", "Tier 5"]),
    "Sustain Ring +5": ItemData(IC.filler, 523, ["Equipment", "Tier 5"]),
    "Crit Ring": ItemData(IC.filler, 524, ["Equipment", "Tier 1"]),
    "Crit Ring +1": ItemData(IC.filler, 525, ["Equipment", "Tier 2"]),
    "Crit Ring +2": ItemData(IC.filler, 526, ["Equipment", "Tier 3"]),
    "Crit Ring +3": ItemData(IC.filler, 527, ["Equipment", "Tier 4"]),
    "Crit Ring +4": ItemData(IC.filler, 528, ["Equipment", "Tier 5"]),
    "Crit Ring +5": ItemData(IC.filler, 529, ["Equipment", "Tier 5"]),
    "Impact Ring": ItemData(IC.filler, 530, ["Equipment", "Tier 1"]),
    "Impact Ring +1": ItemData(IC.filler, 531, ["Equipment", "Tier 2"]),
    "Impact Ring +2": ItemData(IC.filler, 532, ["Equipment", "Tier 3"]),
    "Impact Ring +3": ItemData(IC.filler, 533, ["Equipment", "Tier 4"]),
    "Impact Ring +4": ItemData(IC.filler, 534, ["Equipment", "Tier 5"]),
    "Impact Ring +5": ItemData(IC.filler, 535, ["Equipment", "Tier 5"]),
    "Bandana": ItemData(IC.filler, 536, ["Equipment", "Tier 1"]),
    "Bandana +1": ItemData(IC.filler, 537, ["Equipment", "Tier 2"]),
    "Bandana +2": ItemData(IC.filler, 538, ["Equipment", "Tier 3"]),
    "Bandana +3": ItemData(IC.filler, 539, ["Equipment", "Tier 4"]),
    "Bandana +4": ItemData(IC.filler, 540, ["Equipment", "Tier 5"]),
    "Bandana +5": ItemData(IC.filler, 541, ["Equipment", "Tier 5"]),
    "Belt": ItemData(IC.filler, 542, ["Equipment", "Tier 1"]),
    "Belt +1": ItemData(IC.filler, 543, ["Equipment", "Tier 2"]),
    "Belt +2": ItemData(IC.filler, 544, ["Equipment", "Tier 3"]),
    "Belt +3": ItemData(IC.filler, 545, ["Equipment", "Tier 4"]),
    "Belt +4": ItemData(IC.filler, 546, ["Equipment", "Tier 5"]),
    "Belt +5": ItemData(IC.filler, 547, ["Equipment", "Tier 5"]),
    "Bracelet": ItemData(IC.filler, 548, ["Equipment", "Tier 1"]),
    "Bracelet +1": ItemData(IC.filler, 549, ["Equipment", "Tier 2"]),
    "Bracelet +2": ItemData(IC.filler, 550, ["Equipment", "Tier 3"]),
    "Bracelet +3": ItemData(IC.filler, 551, ["Equipment", "Tier 4"]),
    "Bracelet +4": ItemData(IC.filler, 552, ["Equipment", "Tier 5"]),
    "Bracelet +5": ItemData(IC.filler, 553, ["Equipment", "Tier 5"]),
    "Bracer": ItemData(IC.filler, 554, ["Equipment", "Tier 1"]),
    "Bracer +1": ItemData(IC.filler, 555, ["Equipment", "Tier 2"]),
    "Bracer +2": ItemData(IC.filler, 556, ["Equipment", "Tier 3"]),
    "Bracer +3": ItemData(IC.filler, 557, ["Equipment", "Tier 4"]),
    "Bracer +4": ItemData(IC.filler, 558, ["Equipment", "Tier 5"]),
    "Bracer +5": ItemData(IC.filler, 559, ["Equipment", "Tier 5"]),
    "Cape": ItemData(IC.filler, 560, ["Equipment", "Tier 1"]),
    "Cape +1": ItemData(IC.filler, 561, ["Equipment", "Tier 2"]),
    "Cape +2": ItemData(IC.filler, 562, ["Equipment", "Tier 3"]),
    "Cape +3": ItemData(IC.filler, 563, ["Equipment", "Tier 4"]),
    "Cape +4": ItemData(IC.filler, 564, ["Equipment", "Tier 5"]),
    "Cape +5": ItemData(IC.filler, 565, ["Equipment", "Tier 5"]),
    "Coat": ItemData(IC.filler, 566, ["Equipment", "Tier 1"]),
    "Coat +1": ItemData(IC.filler, 567, ["Equipment", "Tier 2"]),
    "Coat +2": ItemData(IC.filler, 568, ["Equipment", "Tier 3"]),
    "Coat +3": ItemData(IC.filler, 569, ["Equipment", "Tier 4"]),
    "Coat +4": ItemData(IC.filler, 570, ["Equipment", "Tier 5"]),
    "Coat +5": ItemData(IC.filler, 571, ["Equipment", "Tier 5"]),
    "Diadem": ItemData(IC.filler, 572, ["Equipment", "Tier 1"]),
    "Diadem +1": ItemData(IC.filler, 573, ["Equipment", "Tier 2"]),
    "Diadem +2": ItemData(IC.filler, 574, ["Equipment", "Tier 3"]),
    "Diadem +3": ItemData(IC.filler, 575, ["Equipment", "Tier 4"]),
    "Diadem +4": ItemData(IC.filler, 576, ["Equipment", "Tier 5"]),
    "Diadem +5": ItemData(IC.filler, 577, ["Equipment", "Tier 5"]),
    "Fang": ItemData(IC.filler, 578, ["Equipment", "Tier 1"]),
    "Fang +1": ItemData(IC.filler, 579, ["Equipment", "Tier 2"]),
    "Fang +2": ItemData(IC.filler, 580, ["Equipment", "Tier 3"]),
    "Fang +3": ItemData(IC.filler, 581, ["Equipment", "Tier 4"]),
    "Fang +4": ItemData(IC.filler, 582, ["Equipment", "Tier 5"]),
    "Fang +5": ItemData(IC.filler, 583, ["Equipment", "Tier 5"]),
    "Feather": ItemData(IC.filler, 584, ["Equipment", "Tier 1"]),
    "Feather +1": ItemData(IC.filler, 585, ["Equipment", "Tier 2"]),
    "Feather +2": ItemData(IC.filler, 586, ["Equipment", "Tier 3"]),
    "Feather +3": ItemData(IC.filler, 587, ["Equipment", "Tier 4"]),
    "Feather +4": ItemData(IC.filler, 588, ["Equipment", "Tier 5"]),
    "Feather +5": ItemData(IC.filler, 589, ["Equipment", "Tier 5"]),
    "Gauntlet": ItemData(IC.filler, 590, ["Equipment", "Tier 1"]),
    "Gauntlet +1": ItemData(IC.filler, 591, ["Equipment", "Tier 2"]),
    "Gauntlet +2": ItemData(IC.filler, 592, ["Equipment", "Tier 3"]),
    "Gauntlet +3": ItemData(IC.filler, 593, ["Equipment", "Tier 4"]),
    "Gauntlet +4": ItemData(IC.filler, 594, ["Equipment", "Tier 5"]),
    "Gauntlet +5": ItemData(IC.filler, 595, ["Equipment", "Tier 5"]),
    "Helmet": ItemData(IC.filler, 596, ["Equipment", "Tier 1"]),
    "Helmet +1": ItemData(IC.filler, 597, ["Equipment", "Tier 2"]),
    "Helmet +2": ItemData(IC.filler, 598, ["Equipment", "Tier 3"]),
    "Helmet +3": ItemData(IC.filler, 599, ["Equipment", "Tier 4"]),
    "Helmet +4": ItemData(IC.filler, 600, ["Equipment", "Tier 5"]),
    "Helmet +5": ItemData(IC.filler, 601, ["Equipment", "Tier 5"]),
    "Hide": ItemData(IC.filler, 602, ["Equipment", "Tier 1"]),
    "Hide +1": ItemData(IC.filler, 603, ["Equipment", "Tier 2"]),
    "Hide +2": ItemData(IC.filler, 604, ["Equipment", "Tier 3"]),
    "Hide +3": ItemData(IC.filler, 605, ["Equipment", "Tier 4"]),
    "Hide +4": ItemData(IC.filler, 606, ["Equipment", "Tier 5"]),
    "Hide +5": ItemData(IC.filler, 607, ["Equipment", "Tier 5"]),
    "Hood": ItemData(IC.filler, 608, ["Equipment", "Tier 1"]),
    "Hood +1": ItemData(IC.filler, 609, ["Equipment", "Tier 2"]),
    "Hood +2": ItemData(IC.filler, 610, ["Equipment", "Tier 3"]),
    "Hood +3": ItemData(IC.filler, 611, ["Equipment", "Tier 4"]),
    "Hood +4": ItemData(IC.filler, 612, ["Equipment", "Tier 5"]),
    "Hood +5": ItemData(IC.filler, 613, ["Equipment", "Tier 5"]),
    "Needle": ItemData(IC.filler, 614, ["Equipment", "Tier 1"]),
    "Needle +1": ItemData(IC.filler, 615, ["Equipment", "Tier 2"]),
    "Needle +2": ItemData(IC.filler, 616, ["Equipment", "Tier 3"]),
    "Needle +3": ItemData(IC.filler, 617, ["Equipment", "Tier 4"]),
    "Needle+ 4": ItemData(IC.filler, 618, ["Equipment", "Tier 5"]),
    "Needle +5": ItemData(IC.filler, 619, ["Equipment", "Tier 5"]),
    "Ribbon": ItemData(IC.filler, 620, ["Equipment", "Tier 1"]),
    "Ribbon +1": ItemData(IC.filler, 621, ["Equipment", "Tier 2"]),
    "Ribbon +2": ItemData(IC.filler, 622, ["Equipment", "Tier 3"]),
    "Ribbon +3": ItemData(IC.filler, 623, ["Equipment", "Tier 4"]),
    "Ribbon +4": ItemData(IC.filler, 624, ["Equipment", "Tier 5"]),
    "Ribbon +5": ItemData(IC.filler, 625, ["Equipment", "Tier 5"]),
    "Scroll": ItemData(IC.filler, 626, ["Equipment", "Tier 1"]),
    "Scroll +1": ItemData(IC.filler, 627, ["Equipment", "Tier 2"]),
    "Scroll +2": ItemData(IC.filler, 628, ["Equipment", "Tier 3"]),
    "Scroll +3": ItemData(IC.filler, 629, ["Equipment", "Tier 4"]),
    "Scroll +4": ItemData(IC.filler, 630, ["Equipment", "Tier 5"]),
    "Scroll +5": ItemData(IC.filler, 631, ["Equipment", "Tier 5"]),
    "Tome": ItemData(IC.filler, 632, ["Equipment", "Tier 1"]),
    "Tome +1": ItemData(IC.filler, 633, ["Equipment", "Tier 2"]),
    "Tome +2": ItemData(IC.filler, 634, ["Equipment", "Tier 3"]),
    "Tome +3": ItemData(IC.filler, 635, ["Equipment", "Tier 4"]),
    "Tome +4": ItemData(IC.filler, 636, ["Equipment", "Tier 5"]),
    "Tome +5": ItemData(IC.filler, 637, ["Equipment", "Tier 5"]),
    "Wizard Hat": ItemData(IC.filler, 638, ["Equipment", "Tier 1"]),
    "Wizard Hat +1": ItemData(IC.filler, 639, ["Equipment", "Tier 2"]),
    "Wizard Hat +2": ItemData(IC.filler, 640, ["Equipment", "Tier 3"]),
    "Wizard Hat +3": ItemData(IC.filler, 641, ["Equipment", "Tier 4"]),
    "Wizard Hat +4": ItemData(IC.filler, 642, ["Equipment", "Tier 5"]),
    "Wizard Hat +5": ItemData(IC.filler, 643, ["Equipment", "Tier 5"]),

    # Unique Accessories
    "Ancestral Medal": ItemData(IC.filler, 700, ["Equipment", "Tier 1", "Unique"]),
    "Ancestral Medal +1": ItemData(IC.filler, 701, ["Equipment", "Tier 2", "Unique"]),
    "Ancestral Medal +2": ItemData(IC.filler, 702, ["Equipment", "Tier 3", "Unique"]),
    "Ancestral Medal +3": ItemData(IC.filler, 703, ["Equipment", "Tier 4", "Unique"]),
    "Ancestral Medal +4": ItemData(IC.filler, 704, ["Equipment", "Tier 5", "Unique"]),
    "Ancestral Medal +5": ItemData(IC.filler, 705, ["Equipment", "Tier 5", "Unique"]),
    "Bead Chain": ItemData(IC.filler, 706, ["Equipment", "Tier 1", "Unique"]),
    "Bead Chain +1": ItemData(IC.filler, 707, ["Equipment", "Tier 2", "Unique"]),
    "Bead Chain +2": ItemData(IC.filler, 708, ["Equipment", "Tier 3", "Unique"]),
    "Bead Chain +3": ItemData(IC.filler, 709, ["Equipment", "Tier 4", "Unique"]),
    "Bead Chain +4": ItemData(IC.filler, 710, ["Equipment", "Tier 5", "Unique"]),
    "Bead Chain +5": ItemData(IC.filler, 711, ["Equipment", "Tier 5", "Unique"]),
    "Blood Vessel": ItemData(IC.filler, 712, ["Equipment", "Tier 1", "Unique"]),
    "Blood Vessel +1": ItemData(IC.filler, 713, ["Equipment", "Tier 2", "Unique"]),
    "Blood Vessel +2": ItemData(IC.filler, 714, ["Equipment", "Tier 3", "Unique"]),
    "Blood Vessel +3": ItemData(IC.filler, 715, ["Equipment", "Tier 4", "Unique"]),
    "Blood Vessel +4": ItemData(IC.filler, 716, ["Equipment", "Tier 5", "Unique"]),
    "Blood Vessel +5": ItemData(IC.filler, 717, ["Equipment", "Tier 5", "Unique"]),
    "Brooch": ItemData(IC.filler, 718, ["Equipment", "Tier 1", "Unique"]),
    "Brooch +1": ItemData(IC.filler, 719, ["Equipment", "Tier 2", "Unique"]),
    "Brooch +2": ItemData(IC.filler, 720, ["Equipment", "Tier 3", "Unique"]),
    "Brooch +3": ItemData(IC.filler, 721, ["Equipment", "Tier 4", "Unique"]),
    "Brooch +4": ItemData(IC.filler, 722, ["Equipment", "Tier 5", "Unique"]),
    "Brooch +5": ItemData(IC.filler, 723, ["Equipment", "Tier 5", "Unique"]),
    "Buckler": ItemData(IC.filler, 724, ["Equipment", "Tier 1", "Unique"]),
    "Buckler +1": ItemData(IC.filler, 725, ["Equipment", "Tier 2", "Unique"]),
    "Buckler +2": ItemData(IC.filler, 726, ["Equipment", "Tier 3", "Unique"]),
    "Buckler +3": ItemData(IC.filler, 727, ["Equipment", "Tier 4", "Unique"]),
    "Buckler +4": ItemData(IC.filler, 728, ["Equipment", "Tier 5", "Unique"]),
    "Buckler +5": ItemData(IC.filler, 729, ["Equipment", "Tier 5", "Unique"]),
    "Cauldron": ItemData(IC.filler, 730, ["Equipment", "Tier 1", "Unique"]),
    "Cauldron +1": ItemData(IC.filler, 731, ["Equipment", "Tier 2", "Unique"]),
    "Cauldron +2": ItemData(IC.filler, 732, ["Equipment", "Tier 3", "Unique"]),
    "Cauldron +3": ItemData(IC.filler, 733, ["Equipment", "Tier 4", "Unique"]),
    "Cauldron +4": ItemData(IC.filler, 734, ["Equipment", "Tier 5", "Unique"]),
    "Cauldron +5": ItemData(IC.filler, 735, ["Equipment", "Tier 5", "Unique"]),
    "Charging Sphere": ItemData(IC.filler, 736, ["Equipment", "Tier 1", "Unique"]),
    "Charging Sphere+1": ItemData(IC.filler, 737, ["Equipment", "Tier 2", "Unique"]),
    "Charging Sphere+2": ItemData(IC.filler, 738, ["Equipment", "Tier 3", "Unique"]),
    "Charging Sphere+3": ItemData(IC.filler, 739, ["Equipment", "Tier 4", "Unique"]),
    "Charging Sphere+4": ItemData(IC.filler, 740, ["Equipment", "Tier 5", "Unique"]),
    "Charging Sphere+5": ItemData(IC.filler, 741, ["Equipment", "Tier 5", "Unique"]),
    "Crown": ItemData(IC.filler, 742, ["Equipment", "Tier 1", "Unique"]),
    "Crown+1": ItemData(IC.filler, 743, ["Equipment", "Tier 2", "Unique"]),
    "Crown+2": ItemData(IC.filler, 744, ["Equipment", "Tier 3", "Unique"]),
    "Crown+3": ItemData(IC.filler, 745, ["Equipment", "Tier 4", "Unique"]),
    "Crown+4": ItemData(IC.filler, 746, ["Equipment", "Tier 5", "Unique"]),
    "Crown+5": ItemData(IC.filler, 747, ["Equipment", "Tier 5", "Unique"]),
    "Drum": ItemData(IC.filler, 748, ["Equipment", "Tier 1", "Unique"]),
    "Drum +1": ItemData(IC.filler, 749, ["Equipment", "Tier 2", "Unique"]),
    "Drum +2": ItemData(IC.filler, 750, ["Equipment", "Tier 3", "Unique"]),
    "Drum +3": ItemData(IC.filler, 751, ["Equipment", "Tier 4", "Unique"]),
    "Drum +4": ItemData(IC.filler, 752, ["Equipment", "Tier 5", "Unique"]),
    "Drum +5": ItemData(IC.filler, 753, ["Equipment", "Tier 5", "Unique"]),
    "Dumbbell": ItemData(IC.filler, 754, ["Equipment", "Tier 1", "Unique"]),
    "Dumbbell +1": ItemData(IC.filler, 755, ["Equipment", "Tier 2", "Unique"]),
    "Dumbbell +2": ItemData(IC.filler, 756, ["Equipment", "Tier 3", "Unique"]),
    "Dumbbell +3": ItemData(IC.filler, 757, ["Equipment", "Tier 4", "Unique"]),
    "Dumbbell +4": ItemData(IC.filler, 758, ["Equipment", "Tier 5", "Unique"]),
    "Dumbbell +5": ItemData(IC.filler, 759, ["Equipment", "Tier 5", "Unique"]),
    "Fin": ItemData(IC.filler, 760, ["Equipment", "Tier 1", "Unique"]),
    "Fin +1": ItemData(IC.filler, 761, ["Equipment", "Tier 2", "Unique"]),
    "Fin +2": ItemData(IC.filler, 762, ["Equipment", "Tier 3", "Unique"]),
    "Fin +3": ItemData(IC.filler, 763, ["Equipment", "Tier 4", "Unique"]),
    "Fin +4": ItemData(IC.filler, 764, ["Equipment", "Tier 5", "Unique"]),
    "Fin +5": ItemData(IC.filler, 765, ["Equipment", "Tier 5", "Unique"]),
    "Flute": ItemData(IC.filler, 766, ["Equipment", "Tier 1", "Unique"]),
    "Flute +1": ItemData(IC.filler, 767, ["Equipment", "Tier 2", "Unique"]),
    "Flute +2": ItemData(IC.filler, 768, ["Equipment", "Tier 3", "Unique"]),
    "Flute +3": ItemData(IC.filler, 769, ["Equipment", "Tier 4", "Unique"]),
    "Flute +4": ItemData(IC.filler, 770, ["Equipment", "Tier 5", "Unique"]),
    "Flute +5": ItemData(IC.filler, 771, ["Equipment", "Tier 5", "Unique"]),
    "Frozen Tear": ItemData(IC.filler, 772, ["Equipment", "Tier 1", "Unique"]),
    "Frozen Tear +1": ItemData(IC.filler, 773, ["Equipment", "Tier 2", "Unique"]),
    "Frozen Tear +2": ItemData(IC.filler, 774, ["Equipment", "Tier 3", "Unique"]),
    "Frozen Tear +3": ItemData(IC.filler, 775, ["Equipment", "Tier 4", "Unique"]),
    "Frozen Tear +4": ItemData(IC.filler, 776, ["Equipment", "Tier 5", "Unique"]),
    "Frozen Tear +5": ItemData(IC.filler, 777, ["Equipment", "Tier 5", "Unique"]),
    "Gray Pearl": ItemData(IC.filler, 778, ["Equipment", "Tier 1", "Unique"]),
    "Gray Pearl +1": ItemData(IC.filler, 779, ["Equipment", "Tier 2", "Unique"]),
    "Gray Pearl +2": ItemData(IC.filler, 780, ["Equipment", "Tier 3", "Unique"]),
    "Gray Pearl +3": ItemData(IC.filler, 781, ["Equipment", "Tier 4", "Unique"]),
    "Gray Pearl +4": ItemData(IC.filler, 782, ["Equipment", "Tier 5", "Unique"]),
    "Gray Pearl +5": ItemData(IC.filler, 783, ["Equipment", "Tier 5", "Unique"]),
    "Hourglass": ItemData(IC.filler, 784, ["Equipment", "Tier 1", "Unique"]),
    "Hourglass +1": ItemData(IC.filler, 785, ["Equipment", "Tier 2", "Unique"]),
    "Hourglass +2": ItemData(IC.filler, 786, ["Equipment", "Tier 3", "Unique"]),
    "Hourglass +3": ItemData(IC.filler, 787, ["Equipment", "Tier 4", "Unique"]),
    "Hourglass +4": ItemData(IC.filler, 788, ["Equipment", "Tier 5", "Unique"]),
    "Hourglass +5": ItemData(IC.filler, 789, ["Equipment", "Tier 5", "Unique"]),
    "Infinity Flame": ItemData(IC.filler, 790, ["Equipment", "Tier 1", "Unique"]),
    "Infinity Flame +1": ItemData(IC.filler, 791, ["Equipment", "Tier 2", "Unique"]),
    "Infinity Flame +2": ItemData(IC.filler, 792, ["Equipment", "Tier 3", "Unique"]),
    "Infinity Flame +3": ItemData(IC.filler, 793, ["Equipment", "Tier 4", "Unique"]),
    "Infinity Flame +4": ItemData(IC.filler, 794, ["Equipment", "Tier 5", "Unique"]),
    "Infinity Flame +5": ItemData(IC.filler, 795, ["Equipment", "Tier 5", "Unique"]),
    "Lightning Sphere": ItemData(IC.filler, 796, ["Equipment", "Tier 1", "Unique"]),
    "Lightning Sphere +1": ItemData(IC.filler, 797, ["Equipment", "Tier 2", "Unique"]),
    "Lightning Sphere +2": ItemData(IC.filler, 798, ["Equipment", "Tier 3", "Unique"]),
    "Lightning Sphere +3": ItemData(IC.filler, 799, ["Equipment", "Tier 4", "Unique"]),
    "Lightning Sphere +4": ItemData(IC.filler, 800, ["Equipment", "Tier 5", "Unique"]),
    "Lightning Sphere +5": ItemData(IC.filler, 801, ["Equipment", "Tier 5", "Unique"]),
    "Lucky Clover": ItemData(IC.filler, 802, ["Equipment", "Tier 1", "Unique"]),
    "Lucky Clover +1": ItemData(IC.filler, 803, ["Equipment", "Tier 2", "Unique"]),
    "Lucky Clover +2": ItemData(IC.filler, 804, ["Equipment", "Tier 3", "Unique"]),
    "Lucky Clover +3": ItemData(IC.filler, 805, ["Equipment", "Tier 4", "Unique"]),
    "Lucky Clover +4": ItemData(IC.filler, 806, ["Equipment", "Tier 5", "Unique"]),
    "Lucky Clover +5": ItemData(IC.filler, 807, ["Equipment", "Tier 5", "Unique"]),
    "Mage Flask": ItemData(IC.filler, 808, ["Equipment", "Tier 1", "Unique"]),
    "Mage Flask +1": ItemData(IC.filler, 809, ["Equipment", "Tier 2", "Unique"]),
    "Mage Flask +2": ItemData(IC.filler, 810, ["Equipment", "Tier 3", "Unique"]),
    "Mage Flask +3": ItemData(IC.filler, 811, ["Equipment", "Tier 4", "Unique"]),
    "Mage Flask +4": ItemData(IC.filler, 812, ["Equipment", "Tier 5", "Unique"]),
    "Mage Flask +5": ItemData(IC.filler, 813, ["Equipment", "Tier 5", "Unique"]),
    "Medallion": ItemData(IC.filler, 814, ["Equipment", "Tier 1", "Unique"]),
    "Medallion +1": ItemData(IC.filler, 815, ["Equipment", "Tier 2", "Unique"]),
    "Medallion +2": ItemData(IC.filler, 816, ["Equipment", "Tier 3", "Unique"]),
    "Medallion +3": ItemData(IC.filler, 817, ["Equipment", "Tier 4", "Unique"]),
    "Medallion +4": ItemData(IC.filler, 818, ["Equipment", "Tier 5", "Unique"]),
    "Medallion +5": ItemData(IC.filler, 819, ["Equipment", "Tier 5", "Unique"]),
    "Ocarina": ItemData(IC.filler, 820, ["Equipment", "Tier 1", "Unique"]),
    "Ocarina +1": ItemData(IC.filler, 821, ["Equipment", "Tier 2", "Unique"]),
    "Ocarina +2": ItemData(IC.filler, 822, ["Equipment", "Tier 3", "Unique"]),
    "Ocarina +3": ItemData(IC.filler, 823, ["Equipment", "Tier 4", "Unique"]),
    "Ocarina +4": ItemData(IC.filler, 824, ["Equipment", "Tier 5", "Unique"]),
    "Ocarina +5": ItemData(IC.filler, 825, ["Equipment", "Tier 5", "Unique"]),
    "Omni Ring": ItemData(IC.filler, 826, ["Equipment", "Tier 1", "Unique"]),
    "Omni Ring +1": ItemData(IC.filler, 827, ["Equipment", "Tier 2", "Unique"]),
    "Omni Ring +2": ItemData(IC.filler, 828, ["Equipment", "Tier 3", "Unique"]),
    "Omni Ring +3": ItemData(IC.filler, 829, ["Equipment", "Tier 4", "Unique"]),
    "Omni Ring +4": ItemData(IC.filler, 830, ["Equipment", "Tier 5", "Unique"]),
    "Omni Ring +5": ItemData(IC.filler, 831, ["Equipment", "Tier 5", "Unique"]),
    "Ornate Pipe": ItemData(IC.filler, 832, ["Equipment", "Tier 1", "Unique"]),
    "Ornate Pipe +1": ItemData(IC.filler, 833, ["Equipment", "Tier 2", "Unique"]),
    "Ornate Pipe +2": ItemData(IC.filler, 834, ["Equipment", "Tier 3", "Unique"]),
    "Ornate Pipe +3": ItemData(IC.filler, 835, ["Equipment", "Tier 4", "Unique"]),
    "Ornate Pipe +4": ItemData(IC.filler, 836, ["Equipment", "Tier 5", "Unique"]),
    "Ornate Pipe +5": ItemData(IC.filler, 837, ["Equipment", "Tier 5", "Unique"]),
    "Pandora's Box": ItemData(IC.filler, 838, ["Equipment", "Tier 1", "Unique"]),
    "Pandora's Box +1": ItemData(IC.filler, 839, ["Equipment", "Tier 2", "Unique"]),
    "Pandora's Box +2": ItemData(IC.filler, 840, ["Equipment", "Tier 3", "Unique"]),
    "Pandora's Box +3": ItemData(IC.filler, 841, ["Equipment", "Tier 4", "Unique"]),
    "Pandora's Box +4": ItemData(IC.filler, 842, ["Equipment", "Tier 5", "Unique"]),
    "Pandora's Box +5": ItemData(IC.filler, 843, ["Equipment", "Tier 5", "Unique"]),
    "Poisoned Dart": ItemData(IC.filler, 844, ["Equipment", "Tier 1", "Unique"]),
    "Poisoned Dart +1": ItemData(IC.filler, 845, ["Equipment", "Tier 2", "Unique"]),
    "Poisoned Dart +2": ItemData(IC.filler, 846, ["Equipment", "Tier 3", "Unique"]),
    "Poisoned Dart +3": ItemData(IC.filler, 847, ["Equipment", "Tier 4", "Unique"]),
    "Poisoned Dart +4": ItemData(IC.filler, 848, ["Equipment", "Tier 5", "Unique"]),
    "Poisoned Dart +5": ItemData(IC.filler, 849, ["Equipment", "Tier 5", "Unique"]),
    "Shield Generator": ItemData(IC.filler, 850, ["Equipment", "Tier 1", "Unique"]),
    "Shield Generator +1": ItemData(IC.filler, 851, ["Equipment", "Tier 2", "Unique"]),
    "Shield Generator +2": ItemData(IC.filler, 852, ["Equipment", "Tier 3", "Unique"]),
    "Shield Generator +3": ItemData(IC.filler, 853, ["Equipment", "Tier 4", "Unique"]),
    "Shield Generator +4": ItemData(IC.filler, 854, ["Equipment", "Tier 5", "Unique"]),
    "Shield Generator +5": ItemData(IC.filler, 855, ["Equipment", "Tier 5", "Unique"]),
    "Slime Skin": ItemData(IC.filler, 856, ["Equipment", "Tier 1", "Unique"]),
    "Slime Skin +1": ItemData(IC.filler, 857, ["Equipment", "Tier 2", "Unique"]),
    "Slime Skin +2": ItemData(IC.filler, 858, ["Equipment", "Tier 3", "Unique"]),
    "Slime Skin +3": ItemData(IC.filler, 859, ["Equipment", "Tier 4", "Unique"]),
    "Slime Skin +4": ItemData(IC.filler, 860, ["Equipment", "Tier 5", "Unique"]),
    "Slime Skin +5": ItemData(IC.filler, 861, ["Equipment", "Tier 5", "Unique"]),
    "Spark": ItemData(IC.filler, 862, ["Equipment", "Tier 1", "Unique"]),
    "Spark +1": ItemData(IC.filler, 863, ["Equipment", "Tier 2", "Unique"]),
    "Spark +2": ItemData(IC.filler, 864, ["Equipment", "Tier 3", "Unique"]),
    "Spark +3": ItemData(IC.filler, 865, ["Equipment", "Tier 4", "Unique"]),
    "Spark +4": ItemData(IC.filler, 866, ["Equipment", "Tier 5", "Unique"]),
    "Spark +5": ItemData(IC.filler, 867, ["Equipment", "Tier 5", "Unique"]),
    "Sun Pendant": ItemData(IC.filler, 868, ["Equipment", "Tier 1", "Unique"]),
    "Sun Pendant +1": ItemData(IC.filler, 869, ["Equipment", "Tier 2", "Unique"]),
    "Sun Pendant +2": ItemData(IC.filler, 870, ["Equipment", "Tier 3", "Unique"]),
    "Sun Pendant +3": ItemData(IC.filler, 871, ["Equipment", "Tier 4", "Unique"]),
    "Sun Pendant +4": ItemData(IC.filler, 872, ["Equipment", "Tier 5", "Unique"]),
    "Sun Pendant +5": ItemData(IC.filler, 873, ["Equipment", "Tier 5", "Unique"]),
    "Tambourine": ItemData(IC.filler, 874, ["Equipment", "Tier 1", "Unique"]),
    "Tambourine +1": ItemData(IC.filler, 875, ["Equipment", "Tier 2", "Unique"]),
    "Tambourine +2": ItemData(IC.filler, 876, ["Equipment", "Tier 3", "Unique"]),
    "Tambourine +3": ItemData(IC.filler, 877, ["Equipment", "Tier 4", "Unique"]),
    "Tambourine +4": ItemData(IC.filler, 878, ["Equipment", "Tier 5", "Unique"]),
    "Tambourine +5": ItemData(IC.filler, 879, ["Equipment", "Tier 5", "Unique"]),
    "Tarot Card": ItemData(IC.filler, 880, ["Equipment", "Tier 1", "Unique"]),
    "Tarot Card +1": ItemData(IC.filler, 881, ["Equipment", "Tier 2", "Unique"]),
    "Tarot Card +2": ItemData(IC.filler, 882, ["Equipment", "Tier 3", "Unique"]),
    "Tarot Card +3": ItemData(IC.filler, 883, ["Equipment", "Tier 4", "Unique"]),
    "Tarot Card +4": ItemData(IC.filler, 884, ["Equipment", "Tier 5", "Unique"]),
    "Tarot Card +5": ItemData(IC.filler, 885, ["Equipment", "Tier 5", "Unique"]),
    "Thermal Reactor": ItemData(IC.filler, 886, ["Equipment", "Tier 1", "Unique"]),
    "Thermal Reactor +1": ItemData(IC.filler, 887, ["Equipment", "Tier 2", "Unique"]),
    "Thermal Reactor +2": ItemData(IC.filler, 888, ["Equipment", "Tier 3", "Unique"]),
    "Thermal Reactor +3": ItemData(IC.filler, 889, ["Equipment", "Tier 4", "Unique"]),
    "Thermal Reactor +4": ItemData(IC.filler, 890, ["Equipment", "Tier 5", "Unique"]),
    "Thermal Reactor +5": ItemData(IC.filler, 891, ["Equipment", "Tier 5", "Unique"]),
    "Totem": ItemData(IC.filler, 892, ["Equipment", "Tier 1", "Unique"]),
    "Totem +1": ItemData(IC.filler, 893, ["Equipment", "Tier 2", "Unique"]),
    "Totem +2": ItemData(IC.filler, 894, ["Equipment", "Tier 3", "Unique"]),
    "Totem +3": ItemData(IC.filler, 895, ["Equipment", "Tier 4", "Unique"]),
    "Totem +4": ItemData(IC.filler, 896, ["Equipment", "Tier 5", "Unique"]),
    "Totem +5": ItemData(IC.filler, 897, ["Equipment", "Tier 5", "Unique"]),
    "Warrior Flask": ItemData(IC.filler, 898, ["Equipment", "Tier 1", "Unique"]),
    "Warrior Flask +1": ItemData(IC.filler, 899, ["Equipment", "Tier 2", "Unique"]),
    "Warrior Flask +2": ItemData(IC.filler, 900, ["Equipment", "Tier 3", "Unique"]),
    "Warrior Flask +3": ItemData(IC.filler, 901, ["Equipment", "Tier 4", "Unique"]),
    "Warrior Flask +4": ItemData(IC.filler, 902, ["Equipment", "Tier 5", "Unique"]),
    "Warrior Flask +5": ItemData(IC.filler, 903, ["Equipment", "Tier 5", "Unique"]),

    # Relic Accessories
    "Ancient Clock": ItemData(IC.filler, 1000, ["Equipment", "Tier 1", "Unique"]),
    "Ancient Clock +1": ItemData(IC.filler, 1001, ["Equipment", "Tier 2", "Unique"]),
    "Ancient Clock +2": ItemData(IC.filler, 1002, ["Equipment", "Tier 3", "Unique"]),
    "Ancient Clock +3": ItemData(IC.filler, 1003, ["Equipment", "Tier 4", "Unique"]),
    "Ancient Clock +4": ItemData(IC.filler, 1004, ["Equipment", "Tier 5", "Unique"]),
    "Ancient Clock +5": ItemData(IC.filler, 1005, ["Equipment", "Tier 5", "Unique"]),
    "Cursed Drum": ItemData(IC.filler, 1006, ["Equipment", "Tier 1", "Unique"]),
    "Cursed Drum +1": ItemData(IC.filler, 1007, ["Equipment", "Tier 2", "Unique"]),
    "Cursed Drum +2": ItemData(IC.filler, 1008, ["Equipment", "Tier 3", "Unique"]),
    "Cursed Drum +3": ItemData(IC.filler, 1009, ["Equipment", "Tier 4", "Unique"]),
    "Cursed Drum +4": ItemData(IC.filler, 1010, ["Equipment", "Tier 5", "Unique"]),
    "Cursed Drum +5": ItemData(IC.filler, 1011, ["Equipment", "Tier 5", "Unique"]),
    "Devonian Medal": ItemData(IC.filler, 1012, ["Equipment", "Tier 1", "Unique"]),
    "Devonian Medal +1": ItemData(IC.filler, 1013, ["Equipment", "Tier 2", "Unique"]),
    "Devonian Medal +2": ItemData(IC.filler, 1014, ["Equipment", "Tier 3", "Unique"]),
    "Devonian Medal +3": ItemData(IC.filler, 1015, ["Equipment", "Tier 4", "Unique"]),
    "Devonian Medal +4": ItemData(IC.filler, 1016, ["Equipment", "Tier 5", "Unique"]),
    "Devonian Medal +5": ItemData(IC.filler, 1017, ["Equipment", "Tier 5", "Unique"]),
    "Dragon Saddle": ItemData(IC.filler, 1018, ["Equipment", "Tier 1", "Unique"]),
    "Dragon Saddle+1": ItemData(IC.filler, 1019, ["Equipment", "Tier 2", "Unique"]),
    "Dragon Saddle+2": ItemData(IC.filler, 1020, ["Equipment", "Tier 3", "Unique"]),
    "Dragon Saddle+3": ItemData(IC.filler, 1021, ["Equipment", "Tier 4", "Unique"]),
    "Dragon Saddle+4": ItemData(IC.filler, 1022, ["Equipment", "Tier 5", "Unique"]),
    "Dragon Saddle+5": ItemData(IC.filler, 1023, ["Equipment", "Tier 5", "Unique"]),
    "Dwarven Crown": ItemData(IC.filler, 1024, ["Equipment", "Tier 1", "Unique"]),
    "Dwarven Crown +1": ItemData(IC.filler, 1025, ["Equipment", "Tier 2", "Unique"]),
    "Dwarven Crown +2": ItemData(IC.filler, 1026, ["Equipment", "Tier 3", "Unique"]),
    "Dwarven Crown +3": ItemData(IC.filler, 1027, ["Equipment", "Tier 4", "Unique"]),
    "Dwarven Crown +4": ItemData(IC.filler, 1028, ["Equipment", "Tier 5", "Unique"]),
    "Dwarven Crown +5": ItemData(IC.filler, 1029, ["Equipment", "Tier 5", "Unique"]),
    "Earth Symbol": ItemData(IC.filler, 1030, ["Equipment", "Tier 1", "Unique"]),
    "Earth Symbol +1": ItemData(IC.filler, 1031, ["Equipment", "Tier 2", "Unique"]),
    "Earth Symbol +2": ItemData(IC.filler, 1032, ["Equipment", "Tier 3", "Unique"]),
    "Earth Symbol +3": ItemData(IC.filler, 1033, ["Equipment", "Tier 4", "Unique"]),
    "Earth Symbol +4": ItemData(IC.filler, 1034, ["Equipment", "Tier 5", "Unique"]),
    "Earth Symbol +5": ItemData(IC.filler, 1035, ["Equipment", "Tier 5", "Unique"]),
    "Fire Symbol": ItemData(IC.filler, 1036, ["Equipment", "Tier 1", "Unique"]),
    "Fire Symbol+1": ItemData(IC.filler, 1037, ["Equipment", "Tier 2", "Unique"]),
    "Fire Symbol+2": ItemData(IC.filler, 1038, ["Equipment", "Tier 3", "Unique"]),
    "Fire Symbol+3": ItemData(IC.filler, 1039, ["Equipment", "Tier 4", "Unique"]),
    "Fire Symbol+4": ItemData(IC.filler, 1040, ["Equipment", "Tier 5", "Unique"]),
    "Fire Symbol+5": ItemData(IC.filler, 1041, ["Equipment", "Tier 5", "Unique"]),
    "Goblin Garment": ItemData(IC.filler, 1042, ["Equipment", "Tier 1", "Unique"]),
    "Goblin Garment+1": ItemData(IC.filler, 1043, ["Equipment", "Tier 2", "Unique"]),
    "Goblin Garment+2": ItemData(IC.filler, 1044, ["Equipment", "Tier 3", "Unique"]),
    "Goblin Garment+3": ItemData(IC.filler, 1045, ["Equipment", "Tier 4", "Unique"]),
    "Goblin Garment+4": ItemData(IC.filler, 1046, ["Equipment", "Tier 5", "Unique"]),
    "Goblin Garment+5": ItemData(IC.filler, 1047, ["Equipment", "Tier 5", "Unique"]),
    "Gold Feather": ItemData(IC.filler, 1048, ["Equipment", "Tier 1", "Unique"]),
    "Gold Feather +1": ItemData(IC.filler, 1049, ["Equipment", "Tier 2", "Unique"]),
    "Gold Feather +2": ItemData(IC.filler, 1050, ["Equipment", "Tier 3", "Unique"]),
    "Gold Feather +3": ItemData(IC.filler, 1051, ["Equipment", "Tier 4", "Unique"]),
    "Gold Feather +4": ItemData(IC.filler, 1052, ["Equipment", "Tier 5", "Unique"]),
    "Gold Feather +5": ItemData(IC.filler, 1053, ["Equipment", "Tier 5", "Unique"]),
    "Grey Stone": ItemData(IC.filler, 1054, ["Equipment", "Tier 1", "Unique"]),
    "Grey Stone +1": ItemData(IC.filler, 1055, ["Equipment", "Tier 2", "Unique"]),
    "Grey Stone +2": ItemData(IC.filler, 1056, ["Equipment", "Tier 3", "Unique"]),
    "Grey Stone +3": ItemData(IC.filler, 1057, ["Equipment", "Tier 4", "Unique"]),
    "Grey Stone +4": ItemData(IC.filler, 1058, ["Equipment", "Tier 5", "Unique"]),
    "Grey Stone +5": ItemData(IC.filler, 1059, ["Equipment", "Tier 5", "Unique"]),
    "Heavy Greaves": ItemData(IC.filler, 1060, ["Equipment", "Tier 1", "Unique"]),
    "Heavy Greaves +1": ItemData(IC.filler, 1061, ["Equipment", "Tier 2", "Unique"]),
    "Heavy Greaves +2": ItemData(IC.filler, 1062, ["Equipment", "Tier 3", "Unique"]),
    "Heavy Greaves +3": ItemData(IC.filler, 1063, ["Equipment", "Tier 4", "Unique"]),
    "Heavy Greaves +4": ItemData(IC.filler, 1064, ["Equipment", "Tier 5", "Unique"]),
    "Heavy Greaves +5": ItemData(IC.filler, 1065, ["Equipment", "Tier 5", "Unique"]),
    "Holy Necklace": ItemData(IC.filler, 1066, ["Equipment", "Tier 1", "Unique"]),
    "Holy Necklace +1": ItemData(IC.filler, 1067, ["Equipment", "Tier 2", "Unique"]),
    "Holy Necklace +2": ItemData(IC.filler, 1068, ["Equipment", "Tier 3", "Unique"]),
    "Holy Necklace +3": ItemData(IC.filler, 1069, ["Equipment", "Tier 4", "Unique"]),
    "Holy Necklace +4": ItemData(IC.filler, 1070, ["Equipment", "Tier 5", "Unique"]),
    "Holy Necklace +5": ItemData(IC.filler, 1071, ["Equipment", "Tier 5", "Unique"]),
    "Infinity Blaze": ItemData(IC.filler, 1072, ["Equipment", "Tier 1", "Unique"]),
    "Infinity Blaze +1": ItemData(IC.filler, 1073, ["Equipment", "Tier 2", "Unique"]),
    "Infinity Blaze +2": ItemData(IC.filler, 1074, ["Equipment", "Tier 3", "Unique"]),
    "Infinity Blaze +3": ItemData(IC.filler, 1075, ["Equipment", "Tier 4", "Unique"]),
    "Infinity Blaze +4": ItemData(IC.filler, 1076, ["Equipment", "Tier 5", "Unique"]),
    "Infinity Blaze +5": ItemData(IC.filler, 1077, ["Equipment", "Tier 5", "Unique"]),
    "Lion Fang": ItemData(IC.filler, 1078, ["Equipment", "Tier 1", "Unique"]),
    "Lion Fang +1": ItemData(IC.filler, 1079, ["Equipment", "Tier 2", "Unique"]),
    "Lion Fang +2": ItemData(IC.filler, 1080, ["Equipment", "Tier 3", "Unique"]),
    "Lion Fang +3": ItemData(IC.filler, 1081, ["Equipment", "Tier 4", "Unique"]),
    "Lion Fang +4": ItemData(IC.filler, 1082, ["Equipment", "Tier 5", "Unique"]),
    "Lion Fang +5": ItemData(IC.filler, 1083, ["Equipment", "Tier 5", "Unique"]),
    "Moon Ring": ItemData(IC.filler, 1084, ["Equipment", "Tier 1", "Unique"]),
    "Moon Ring +1": ItemData(IC.filler, 1085, ["Equipment", "Tier 2", "Unique"]),
    "Moon Ring +2": ItemData(IC.filler, 1086, ["Equipment", "Tier 3", "Unique"]),
    "Moon Ring +3": ItemData(IC.filler, 1087, ["Equipment", "Tier 4", "Unique"]),
    "Moon Ring +4": ItemData(IC.filler, 1088, ["Equipment", "Tier 5", "Unique"]),
    "Moon Ring +5": ItemData(IC.filler, 1089, ["Equipment", "Tier 5", "Unique"]),
    "Nimble Wings": ItemData(IC.filler, 1090, ["Equipment", "Tier 1", "Unique"]),
    "Nimble Wings +1": ItemData(IC.filler, 1091, ["Equipment", "Tier 2", "Unique"]),
    "Nimble Wings +2": ItemData(IC.filler, 1092, ["Equipment", "Tier 3", "Unique"]),
    "Nimble Wings +3": ItemData(IC.filler, 1093, ["Equipment", "Tier 4", "Unique"]),
    "Nimble Wings +4": ItemData(IC.filler, 1094, ["Equipment", "Tier 5", "Unique"]),
    "Nimble Wings +5": ItemData(IC.filler, 1095, ["Equipment", "Tier 5", "Unique"]),
    "Pandora's Chest": ItemData(IC.filler, 1096, ["Equipment", "Tier 1", "Unique"]),
    "Pandora's Chest +1": ItemData(IC.filler, 1097, ["Equipment", "Tier 2", "Unique"]),
    "Pandora's Chest +2": ItemData(IC.filler, 1098, ["Equipment", "Tier 3", "Unique"]),
    "Pandora's Chest +3": ItemData(IC.filler, 1099, ["Equipment", "Tier 4", "Unique"]),
    "Pandora's Chest +4": ItemData(IC.filler, 1100, ["Equipment", "Tier 5", "Unique"]),
    "Pandora's Chest +5": ItemData(IC.filler, 1101, ["Equipment", "Tier 5", "Unique"]),
    "Pure Leaf": ItemData(IC.filler, 1102, ["Equipment", "Tier 1", "Unique"]),
    "Pure Leaf +1": ItemData(IC.filler, 1103, ["Equipment", "Tier 2", "Unique"]),
    "Pure Leaf +2": ItemData(IC.filler, 1104, ["Equipment", "Tier 3", "Unique"]),
    "Pure Leaf +3": ItemData(IC.filler, 1105, ["Equipment", "Tier 4", "Unique"]),
    "Pure Leaf +4": ItemData(IC.filler, 1106, ["Equipment", "Tier 5", "Unique"]),
    "Pure Leaf +5": ItemData(IC.filler, 1107, ["Equipment", "Tier 5", "Unique"]),
    "Reptilian Idol": ItemData(IC.filler, 1108, ["Equipment", "Tier 1", "Unique"]),
    "Reptilian Idol +1": ItemData(IC.filler, 1109, ["Equipment", "Tier 2", "Unique"]),
    "Reptilian Idol +2": ItemData(IC.filler, 1110, ["Equipment", "Tier 3", "Unique"]),
    "Reptilian Idol +3": ItemData(IC.filler, 1111, ["Equipment", "Tier 4", "Unique"]),
    "Reptilian Idol +4": ItemData(IC.filler, 1112, ["Equipment", "Tier 5", "Unique"]),
    "Reptilian Idol +5": ItemData(IC.filler, 1113, ["Equipment", "Tier 5", "Unique"]),
    "Sharp Fin": ItemData(IC.filler, 1114, ["Equipment", "Tier 1", "Unique"]),
    "Sharp Fin +1": ItemData(IC.filler, 1115, ["Equipment", "Tier 2", "Unique"]),
    "Sharp Fin +2": ItemData(IC.filler, 1116, ["Equipment", "Tier 3", "Unique"]),
    "Sharp Fin +3": ItemData(IC.filler, 1117, ["Equipment", "Tier 4", "Unique"]),
    "Sharp Fin +4": ItemData(IC.filler, 1118, ["Equipment", "Tier 5", "Unique"]),
    "Sharp Fin +5": ItemData(IC.filler, 1119, ["Equipment", "Tier 5", "Unique"]),
    "Slimy Ball": ItemData(IC.filler, 1120, ["Equipment", "Tier 1", "Unique"]),
    "Slimy Ball +1": ItemData(IC.filler, 1121, ["Equipment", "Tier 2", "Unique"]),
    "Slimy Ball +2": ItemData(IC.filler, 1122, ["Equipment", "Tier 3", "Unique"]),
    "Slimy Ball +3": ItemData(IC.filler, 1123, ["Equipment", "Tier 4", "Unique"]),
    "Slimy Ball +4": ItemData(IC.filler, 1124, ["Equipment", "Tier 5", "Unique"]),
    "Slimy Ball +5": ItemData(IC.filler, 1125, ["Equipment", "Tier 5", "Unique"]),
    "Spirit Blaze": ItemData(IC.filler, 1126, ["Equipment", "Tier 1", "Unique"]),
    "Spirit Blaze +1": ItemData(IC.filler, 1127, ["Equipment", "Tier 2", "Unique"]),
    "Spirit Blaze +2": ItemData(IC.filler, 1128, ["Equipment", "Tier 3", "Unique"]),
    "Spirit Blaze +3": ItemData(IC.filler, 1129, ["Equipment", "Tier 4", "Unique"]),
    "Spirit Blaze +4": ItemData(IC.filler, 1130, ["Equipment", "Tier 5", "Unique"]),
    "Spirit Blaze +5": ItemData(IC.filler, 1131, ["Equipment", "Tier 5", "Unique"]),
    "Static Loop": ItemData(IC.filler, 1132, ["Equipment", "Tier 1", "Unique"]),
    "Static Loop +1": ItemData(IC.filler, 1133, ["Equipment", "Tier 2", "Unique"]),
    "Static Loop +2": ItemData(IC.filler, 1134, ["Equipment", "Tier 3", "Unique"]),
    "Static Loop +3": ItemData(IC.filler, 1135, ["Equipment", "Tier 4", "Unique"]),
    "Static Loop +4": ItemData(IC.filler, 1136, ["Equipment", "Tier 5", "Unique"]),
    "Static Loop +5": ItemData(IC.filler, 1137, ["Equipment", "Tier 5", "Unique"]),
    "Sun Ring": ItemData(IC.filler, 1138, ["Equipment", "Tier 1", "Unique"]),
    "Sun Ring +1": ItemData(IC.filler, 1139, ["Equipment", "Tier 2", "Unique"]),
    "Sun Ring +2": ItemData(IC.filler, 1140, ["Equipment", "Tier 3", "Unique"]),
    "Sun Ring +3": ItemData(IC.filler, 1141, ["Equipment", "Tier 4", "Unique"]),
    "Sun Ring +4": ItemData(IC.filler, 1142, ["Equipment", "Tier 5", "Unique"]),
    "Sun Ring +5": ItemData(IC.filler, 1143, ["Equipment", "Tier 5", "Unique"]),
    "Toxic Pot": ItemData(IC.filler, 1144, ["Equipment", "Tier 1", "Unique"]),
    "Toxic Pot +1": ItemData(IC.filler, 1145, ["Equipment", "Tier 2", "Unique"]),
    "Toxic Pot +2": ItemData(IC.filler, 1146, ["Equipment", "Tier 3", "Unique"]),
    "Toxic Pot +3": ItemData(IC.filler, 1147, ["Equipment", "Tier 4", "Unique"]),
    "Toxic Pot +4": ItemData(IC.filler, 1148, ["Equipment", "Tier 5", "Unique"]),
    "Toxic Pot +5": ItemData(IC.filler, 1149, ["Equipment", "Tier 5", "Unique"]),
    "Warlock Hat": ItemData(IC.filler, 1150, ["Equipment", "Tier 1", "Unique"]),
    "Warlock Hat +1": ItemData(IC.filler, 1151, ["Equipment", "Tier 2", "Unique"]),
    "Warlock Hat +2": ItemData(IC.filler, 1152, ["Equipment", "Tier 3", "Unique"]),
    "Warlock Hat +3": ItemData(IC.filler, 1153, ["Equipment", "Tier 4", "Unique"]),
    "Warlock Hat +4": ItemData(IC.filler, 1154, ["Equipment", "Tier 5", "Unique"]),
    "Warlock Hat +5": ItemData(IC.filler, 1155, ["Equipment", "Tier 5", "Unique"]),
    "Water Symbol": ItemData(IC.filler, 1156, ["Equipment", "Tier 1", "Unique"]),
    "Water Symbol +1": ItemData(IC.filler, 1157, ["Equipment", "Tier 2", "Unique"]),
    "Water Symbol +2": ItemData(IC.filler, 1158, ["Equipment", "Tier 3", "Unique"]),
    "Water Symbol +3": ItemData(IC.filler, 1159, ["Equipment", "Tier 4", "Unique"]),
    "Water Symbol +4": ItemData(IC.filler, 1160, ["Equipment", "Tier 5", "Unique"]),
    "Water Symbol +5": ItemData(IC.filler, 1161, ["Equipment", "Tier 5", "Unique"]),
    "Wind Symbol": ItemData(IC.filler, 1162, ["Equipment", "Tier 1", "Unique"]),
    "Wind Symbol +1": ItemData(IC.filler, 1163, ["Equipment", "Tier 2", "Unique"]),
    "Wind Symbol +2": ItemData(IC.filler, 1164, ["Equipment", "Tier 3", "Unique"]),
    "Wind Symbol +3": ItemData(IC.filler, 1165, ["Equipment", "Tier 4", "Unique"]),
    "Wind Symbol +4": ItemData(IC.filler, 1166, ["Equipment", "Tier 5", "Unique"]),
    "Wind Symbol +5": ItemData(IC.filler, 1167, ["Equipment", "Tier 5", "Unique"]),

    # Gold

    # Monsters
    "Blob": ItemData(IC.progression, 2119, ["Monster", "Bubble Burst", "Water Orbs"]),
    "Vaero": ItemData(IC.progression, 2151, ["Monster", "Flying", "Distant Ledges"]),
    "Magmapillar": ItemData(IC.progression, 2169, ["Monster", "Ignite", "Impassible Vines", "Flame Orbs", "Torches"]),
    "Spectral Wolf": ItemData(IC.progression, 2228, ["Monster", "Tackle", "Breakable Walls", "Impassible Vines"]),
    "Rocky": ItemData(IC.progression, 2237, ["Monster", "Summon Rock", "Ground Switches"]),
    "Catzerker": ItemData(IC.progression, 2238, ["Monster", "Slash", "Impassible Vines", "Breakable Walls"]),
    "Spectral Toad": ItemData(IC.progression, 2317, ["Monster", "Tackle", "Breakable Walls", "Heavy Blocks"]),
    "Spectral Eagle": ItemData(IC.progression, 2348, ["Monster", "Flying", "Distant Ledges"]),
    "Spectral Lion": ItemData(IC.progression, 2361, ["Monster", "Claws", "Breakable Walls", "Impassible Vines"]),
    "Yowie": ItemData(IC.progression, 2375, ["Monster", "Tackle", "Breakable Walls", "Heavy Blocks"]),
    "Tanuki": ItemData(IC.progression, 2930, ["Monster", "Summon Mushroom", "Ground Switches"]),
    "Manticorb": ItemData(IC.progression, 3037, ["Monster", "Light", "Dark Rooms"])
}


def build_item_groups():
    item_groups = {}
    for item, data in item_table.items():
        for group in data.groups:
            item_groups[group] = item_groups.get(group, []) + [item]
