from enum import IntFlag
from typing import List, Dict, Optional
from BaseClasses import ItemClassification as IC
from BaseClasses import MultiWorld, Item
from worlds.AutoWorld import World


class ItemData:
    id: int

    def __init__(self, classification, groups):
        self.classification = classification
        self.groups = groups


class MonsterSanctuaryItem(Item):
    game: str = "Monster Sanctuary"
    quantity: int = 1

    def __init__(self, name, data: ItemData, player: int = None):
        super(MonsterSanctuaryItem, self).__init__(
            name,
            data.classification,
            data.id,
            player)


def build_item_ids():
    i = 0
    for item in item_table.values():
        item.id = 970500+ i
        i+= 1


def build_item_groups():
    item_groups = {}
    for item, data in item_table.items():
        for group in data.groups:
            item_groups[group] = item_groups.get(group, [])+ [item]

    return item_groups


def get_filler_item_name(world: World, itempool: List[MonsterSanctuaryItem]) -> str:
    """Needs work"""
    return world.random.choice(
        [item for item in get_filtered_unique_item_data(itempool)
         if item_table[item].classification == IC.filler])


def get_item_name_from_group(world: World, itempool: List[MonsterSanctuaryItem], *groups) -> str:
    """Returns the name of a random item with any of the given group names from the item list"""
    return world.random.choice(
        [item for item in get_filtered_unique_item_data(itempool)
         if is_item_in_group(item, *groups)]
    )


def get_item_name_not_in_group(world: World, itempool: List[MonsterSanctuaryItem], *groups):
    """Returns the name of a random item with none of the given group names from the item list"""
    return world.random.choice(
        [item for item in get_filtered_unique_item_data(itempool)
         if not is_item_in_group(item, *groups)]
    )


def get_filtered_unique_item_data(itempool: List[MonsterSanctuaryItem]) -> Dict[str, ItemData]:
    """Given a list of items, this returns a subset of that list with unique items removed
    if the unique item is already in the item pool"""
    return {item: item_table[item] for item in item_table
            if not is_item_in_group(item, "Unique")
            or not is_in_item_pool(item, itempool)}


def is_item_in_group(item: str, *groups: str):
    """Checks to see fi the item is in any of the given groups"""
    # If there's on groups to check, then we return true
    if len(groups) == 0:
        return True
    return not set(item_table[item].groups).isdisjoint(groups)


def is_in_item_pool(item: str, itempool: List[MonsterSanctuaryItem]) -> bool:
    """Checks to see if the item name is already in the item pool"""
    return item in [pool_item.name for pool_item in itempool]


def get_random_item_name(world: World,
                         itempool: List[MonsterSanctuaryItem],
                         group_include: List[str] = None,
                         group_exclude: List[str] = None) -> Optional[str]:
    """Gets a random item name from the master item list with the following restrictions:
    Unique items already in the item pool will not be added a second time
    Items with groups that intersect with group_exclude will not be added
    Only items whose groups intersect with group_include will be selected from"""
    if group_include is None:
        group_include = []
    if group_exclude is None:
        group_exclude = []

    # We should never return multiple items, those require special randomization
    # that happens down below
    if "Multiple" not in group_exclude:
        group_exclude.append("Multiple")

    # Not Worrying about tier right now
    # if tier is not None:
    #     group_filter.append("Tier " + str(tier))

    valid_items = [item for item in get_filtered_unique_item_data(itempool)
                   if is_item_in_group(item, *group_include)
                   and not is_item_in_group(item, *group_exclude)]

    if len(valid_items) == 0:
        return None

    base_item_name = world.random.choice(valid_items)
    base_item = item_table.get(base_item_name)

    name_prepend = None
    if "Up to 2" in base_item.groups:
        roll = world.random.randint(1, 10)
        if roll >= 7:
            name_prepend = "2x"
    elif "Up to 3" in base_item.groups:
        roll = world.random.randint(1, 10)
        if roll >= 9:
            name_prepend = "3x"
        elif roll >= 6:
            name_prepend = "2x"

    if name_prepend is not None:
        new_item_name = name_prepend + " " + base_item_name
        if new_item_name is not None and item_table.get(new_item_name) is not None:
            base_item_name = new_item_name

    return base_item_name


item_table = {
    # Key Items
    "Sanctuary Token": ItemData(IC.progression, ["Key Item"]),
    "Double Jump Boots": ItemData(IC.progression, ["Key Item", "Unique"]),
    "Warm Underwear": ItemData(IC.progression, ["Key Item", "Unique"]),
    "Runestone Shard": ItemData(IC.progression, ["Key Item", "Unique"]),
    "Key of Power": ItemData(IC.progression, ["Key Item", "Unique"]),
    "Ahrimaaya": ItemData(IC.progression, ["Key Item", "Unique"]),
    "Blob Key": ItemData(IC.progression, ["Key Item", "Unique"]),
    "Mozzie": ItemData(IC.progression, ["Key Item", "Unique"]),
    "Rare Seashell": ItemData(IC.progression, ["Key Item"]),
    "Celestial Feather": ItemData(IC.progression, ["Key Item"]),
    "Mountain Path Key": ItemData(IC.progression, ["Key Item", "Area Key"]),
    "Blue Caves Key": ItemData(IC.progression, ["Key Item", "Area Key"]),
    "Stronghold Dungeon Key": ItemData(IC.progression, ["Key Item", "Area Key"]),
    "Ancient Woods Key": ItemData(IC.progression, ["Key Item", "Area Key"]),
    "Magma Chamber Key": ItemData(IC.progression, ["Key Item", "Area Key"]),
    "Mystical Workshop Key": ItemData(IC.progression, ["Key Item", "Area Key"]),
    "Underworld Key": ItemData(IC.progression, ["Key Item", "Area Key"]),

    # Crafting Materials
    "Copper": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Up to 3"]),
    "2x Copper": ItemData(IC.filler, ["Crafting Materials", "Tier 1"]),
    "3x Copper": ItemData(IC.filler, ["Crafting Materials", "Tier 1"]),
    "Iron": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Up to 3"]),
    "2x Iron": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Multiple"]),
    "3x Iron": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Multiple"]),
    "Bronze": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Up to 3"]),
    "2x Bronze": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Multiple"]),
    "3x Bronze": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Multiple"]),
    "Steel": ItemData(IC.filler, ["Crafting Materials", "Tier 4", "Up to 2"]),
    "2x Steel": ItemData(IC.filler, ["Crafting Materials", "Tier 4", "Multiple"]),
    "Silver": ItemData(IC.filler, ["Crafting Materials", "Tier 4", "Up to 2"]),
    "2x Silver": ItemData(IC.filler, ["Crafting Materials", "Tier 4", "Multiple"]),
    "Gold": ItemData(IC.filler, ["Crafting Materials", "Tier 5"]),
    "Cotton": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Up to 3"]),
    "2x Cotton": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Multiple"]),
    "3x Cotton": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Multiple"]),
    "Wool": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Up to 3"]),
    "2x Wool": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Multiple"]),
    "3x Wool": ItemData(IC.filler, ["Crafting Materials", "Tier 2", "Multiple"]),
    "Leather": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Up to 3"]),
    "2x Leather": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Multiple"]),
    "3x Leather": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Multiple"]),
    # Raw Hide unlocks a check, so it has to be progression
    "Raw Hide": ItemData(IC.progression, ["Crafting Materials", "Tier 3"]),
    "Silk": ItemData(IC.filler, ["Crafting Materials", "Tier 4"]),
    "2x Silk": ItemData(IC.filler, ["Crafting Materials", "Tier 4", "Multiple"]),
    "Linen": ItemData(IC.filler, ["Crafting Materials", "Tier 5"]),
    "Red Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Up to 3"]),
    "2x Red Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Multiple"]),
    "3x Red Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Multiple"]),
    "Green Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Up to 3"]),
    "2x Green Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Multiple"]),
    "3x Green Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Multiple"]),
    "Blue Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Up to 3"]),
    "2x Blue Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Multiple"]),
    "3x Blue Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 1", "Multiple"]),
    "Crimson Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Up to 2"]),
    "2x Crimson Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Multiple"]),
    "Verdant Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Up to 2"]),
    "2x Verdant Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Multiple"]),
    "Azure Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Up to 2"]),
    "2x Azure Gem": ItemData(IC.filler, ["Crafting Materials", "Tier 3", "Multiple"]),
    "Ruby": ItemData(IC.filler, ["Crafting Materials", "Tier 5"]),
    "Emerald": ItemData(IC.filler, ["Crafting Materials", "Tier 5"]),
    "Sapphire": ItemData(IC.filler, ["Crafting Materials", "Tier 5"]),

    # Consumables
    # this might need to be adjusted, because teleporting to keeper stronghold early might break things
    "Crystal Shard": ItemData(IC.filler, ["Consumable", "Up to 3"]),
    "2x Crystal Shard": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "3x Crystal Shard": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "Monster Bell": ItemData(IC.filler, ["Consumable", "Up to 2"]),
    "2x Monster Bell": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "Skill Resetter": ItemData(IC.filler, ["Consumable", "Up to 2"]),
    "2x Skill Resetter": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "Skill Potion": ItemData(IC.useful, ["Consumable"]),
    "Level Badge": ItemData(IC.useful, ["Consumable"]),
    # the below tiers might be off and need balancing
    "Level Badge 42": ItemData(IC.useful, ["Consumable", "Tier 5"]),
    "Shift Stone": ItemData(IC.useful, ["Consumable", "Tier 3", "Up to 2"]),
    "2x Shift Stone": ItemData(IC.useful, ["Consumable", "Tier 3", "Multiple"]),
    "Switch Stone": ItemData(IC.useful, ["Consumable", "Tier 3", "Up to 2"]),
    "2x Switch Stone": ItemData(IC.useful, ["Consumable", "Tier 3", "Multiple"]),
    "Clear Stone": ItemData(IC.filler, ["Consumable", "Tier 3", "Up to 2"]),
    "2x Clear Stone": ItemData(IC.filler, ["Consumable", "Tier 3", "Multiple"]),
    "Craft Box": ItemData(IC.filler, ["Consumable", "Up to 3"]),
    "2x Craft Box": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "3x Craft Box": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "Reward Box Lvl 1": ItemData(IC.useful, ["Consumable", "Tier 1"]),
    "Reward Box Lvl 2": ItemData(IC.useful, ["Consumable", "Tier 2"]),
    "Reward Box Lvl 3": ItemData(IC.useful, ["Consumable", "Tier 3"]),
    "Reward Box Lvl 4": ItemData(IC.useful, ["Consumable", "Tier 4"]),
    "Reward Box Lvl 5": ItemData(IC.useful, ["Consumable", "Tier 5"]),
    "Reward Box X": ItemData(IC.useful, ["Consumable", "Tier 5"]),
    "Small Potion": ItemData(IC.filler, ["Consumable", "Tier 1", "Up to 3"]),
    "2x Small Potion": ItemData(IC.filler, ["Consumable", "Tier 1", "Multiple"]),
    "3x Small Potion": ItemData(IC.filler, ["Consumable", "Tier 1", "Multiple"]),
    "Potion": ItemData(IC.filler, ["Consumable", "Tier 2", "Up to 3"]),
    "2x Potion": ItemData(IC.filler, ["Consumable", "Tier 2", "Multiple"]),
    "3x Potion": ItemData(IC.filler, ["Consumable", "Tier 2", "Multiple"]),
    "Mass Potion": ItemData(IC.useful, ["Consumable", "Tier 3"]),
    "Combo Potion": ItemData(IC.filler, ["Consumable", "Tier 3"]),
    "Big Potion": ItemData(IC.filler, ["Consumable", "Tier 4"]),
    "Mega Potion": ItemData(IC.filler, ["Consumable", "Tier 5"]),
    "Antidote": ItemData(IC.filler, ["Consumable", "Tier 1", "Up to 3"]),
    "2x Antidote": ItemData(IC.filler, ["Consumable", "Tier 1", "Multiple"]),
    "3x Antidote": ItemData(IC.filler, ["Consumable", "Tier 1", "Multiple"]),
    "Mass Antidote": ItemData(IC.filler, ["Consumable", "Tier 2"]),
    "Phoenix Tear": ItemData(IC.filler, ["Consumable", "Up to 3"]),
    "2x Phoenix Tear": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "3x Phoenix Tear": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "Phoenix Serum": ItemData(IC.filler, ["Consumable", "Tier 3"]),
    "Smoke Bomb": ItemData(IC.filler, ["Consumable", "Up to 3"]),
    "2x Smoke Bomb": ItemData(IC.filler, ["Consumable", "Multiple"]),
    "3x Smoke Bomb": ItemData(IC.filler, ["Consumable", "Multiple"]),

    # Foods
    "Walnut": ItemData(IC.filler, ["Food", "Tier 1", "Up to 3"]),
    "2x Walnut": ItemData(IC.filler, ["Food", "Tier 1", "Multiple"]),
    "3x Walnut": ItemData(IC.filler, ["Food", "Tier 1", "Multiple"]),
    "Hazelnut": ItemData(IC.filler, ["Food", "Tier 2", "Up to 3"]),
    "2x Hazelnut": ItemData(IC.filler, ["Food", "Tier 2", "Multiple"]),
    "3x Hazelnut": ItemData(IC.filler, ["Food", "Tier 2", "Multiple"]),
    "Almond": ItemData(IC.filler, ["Food", "Tier 3", "Up to 2"]),
    "2x Almond": ItemData(IC.filler, ["Food", "Tier 3", "Multiple"]),
    "Peanut": ItemData(IC.filler, ["Food", "Tier 4"]),
    "Potato": ItemData(IC.filler, ["Food", "Tier 1", "Up to 3"]),
    "2x Potato": ItemData(IC.filler, ["Food", "Tier 1", "Multiple"]),
    "3x Potato": ItemData(IC.filler, ["Food", "Tier 1", "Multiple"]),
    "Corn": ItemData(IC.filler, ["Food", "Tier 2", "Up to 3"]),
    "2x Corn": ItemData(IC.filler, ["Food", "Tier 2", "Multiple"]),
    "3x Corn": ItemData(IC.filler, ["Food", "Tier 2", "Multiple"]),
    "Carrot": ItemData(IC.filler, ["Food", "Tier 3", "Up to 2"]),
    "2x Carrot": ItemData(IC.filler, ["Food", "Tier 3", "Multiple"]),
    "Banana": ItemData(IC.filler, ["Food", "Tier 4"]),
    "Apple": ItemData(IC.filler, ["Food", "Tier 1", "Up to 3"]),
    "2x Apple": ItemData(IC.filler, ["Food", "Tier 1", "Multiple"]),
    "3x Apple": ItemData(IC.filler, ["Food", "Tier 1", "Multiple"]),
    "Pear": ItemData(IC.filler, ["Food", "Tier 2", "Up to 3"]),
    "2x Pear": ItemData(IC.filler, ["Food", "Tier 2", "Multiple"]),
    "3x Pear": ItemData(IC.filler, ["Food", "Tier 2", "Multiple"]),
    "Mango": ItemData(IC.filler, ["Food", "Tier 3", "Up to 2"]),
    "2x Mango": ItemData(IC.filler, ["Food", "Tier 3", "Multiple"]),
    "Orange": ItemData(IC.filler, ["Food", "Tier 4"]),
    "Berry": ItemData(IC.filler, ["Food", "Tier 1", "Up to 3"]),
    "2x Berry": ItemData(IC.filler, ["Food", "Tier 1", "Multiple"]),
    "3x Berry": ItemData(IC.filler, ["Food", "Tier 1", "Multiple"]),
    "Grapes": ItemData(IC.filler, ["Food", "Tier 2", "Up to 3"]),
    "2x Grapes": ItemData(IC.filler, ["Food", "Tier 2", "Multiple"]),
    "3x Grapes": ItemData(IC.filler, ["Food", "Tier 2", "Multiple"]),
    "Strawberry": ItemData(IC.filler, ["Food", "Tier 3", "Up to 2"]),
    "2x Strawberry": ItemData(IC.filler, ["Food", "Tier 3", "Multiple"]),
    "Raspberry": ItemData(IC.filler, ["Food", "Tier 4"]),
    "Cookie Mushroom": ItemData(IC.filler, ["Food"]),

    # Catalysts
    "Stardust": ItemData(IC.useful, ["Catalyst"]),
    "Cocoon": ItemData(IC.useful, ["Catalyst"]),
    "Shard of Winter": ItemData(IC.useful, ["Catalyst"]),
    "Magical Clay": ItemData(IC.useful, ["Catalyst"]),
    "Sun Stone": ItemData(IC.useful, ["Catalyst"]),
    "Silver Feather": ItemData(IC.useful, ["Catalyst"]),
    "Volcanic Ash": ItemData(IC.useful, ["Catalyst"]),
    "Fire Stone": ItemData(IC.useful, ["Catalyst"]),
    "Ice Stone": ItemData(IC.useful, ["Catalyst"]),
    "Giant Seed": ItemData(IC.useful, ["Catalyst"]),
    "Dark Stone": ItemData(IC.useful, ["Catalyst"]),
    "Majestic Crown": ItemData(IC.useful, ["Catalyst"]),
    "Demonic Pact": ItemData(IC.useful, ["Catalyst"]),
    "Primordial Branch": ItemData(IC.useful, ["Catalyst"]),
    "Druid Soul": ItemData(IC.useful, ["Catalyst"]),
    "Deep Stone": ItemData(IC.useful, ["Catalyst"]),

    # Basic Weapons
    "Morning Star": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Morning Star+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Morning Star+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Morning Star+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Morning Star+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Morning Star+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Claws": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Claws+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Claws+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Claws+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Claws+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Claws+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Katar": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Katar+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Katar+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Katar+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Katar+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Katar+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Wand": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Wand+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Wand+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Wand+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Wand+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Wand+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Orb": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Orb+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Orb+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Orb+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Orb+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Orb+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Staff": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Staff+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Staff+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Staff+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Staff+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Staff+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Cestus": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Cestus+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Cestus+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Cestus+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Cestus+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Cestus+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Kunai": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Kunai+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Kunai+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Kunai+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Kunai+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Kunai+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Shuriken": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Shuriken+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Shuriken+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Shuriken+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Shuriken+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Shuriken+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),

    # Unique Weapons
    "Abyssal Sword": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Abyssal Sword+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Abyssal Sword+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Abyssal Sword+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Abyssal Sword+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Abyssal Sword+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Bow": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Bow+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Bow+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Bow+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Bow+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Bow+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fan": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Fan+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Fan+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Fan+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Fan+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fan+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fishing Rod": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Fishing Rod+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Fishing Rod+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Fishing Rod+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Fishing Rod+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fishing Rod+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Hammer": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Hammer+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Hammer+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Hammer+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Hammer+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Hammer+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Harp": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Harp+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Harp+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Harp+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Harp+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Harp+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Heavy Mace": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Heavy Mace+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Heavy Mace+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Heavy Mace+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Heavy Mace+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Heavy Mace+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Hexing Rod": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Hexing Rod+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Hexing Rod+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Hexing Rod+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Hexing Rod+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Hexing Rod+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Katana": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Katana+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Katana+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Katana+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Katana+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Katana+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Large Shield": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Large Shield+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Large Shield+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Large Shield+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Large Shield+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Large Shield+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Mandolin ": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Mandolin+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Mandolin+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Mandolin+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Mandolin+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Mandolin+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Moon Sword": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Moon Sword+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Moon Sword+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Moon Sword+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Moon Sword+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Moon Sword+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Pirate Hook": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Pirate Hook+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Pirate Hook+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Pirate Hook+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Pirate Hook+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Pirate Hook+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Purifying Mace": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Purifying Mace+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Purifying Mace+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Purifying Mace+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Purifying Mace+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Purifying Mace+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Restoring Wand": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Restoring Wand+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Restoring Wand+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Restoring Wand+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Restoring Wand+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Restoring Wand+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Scepter": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Scepter+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Scepter+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Scepter+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Scepter+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Scepter+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Scythe": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Scythe+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Scythe+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Scythe+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Scythe+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Scythe+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Summoned Sword": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Summoned Sword+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Summoned Sword+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Summoned Sword+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Summoned Sword+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Summoned Sword+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Swallow": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Swallow+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Swallow+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Swallow+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Swallow+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Swallow+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Thorn Tendril": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Thorn Tendril+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Thorn Tendril+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Thorn Tendril+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Thorn Tendril+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Thorn Tendril+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Torch": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Torch+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Torch+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Torch+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Torch+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Torch+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Trident": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Trident+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Trident+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Trident+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Trident+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Trident+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Warhorn": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Warhorn+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Warhorn+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Warhorn+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Warhorn+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Warhorn+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),

    # Relic Weapons
    "Arch Bow": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Arch Bow+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Arch Bow+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Arch Bow+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Arch Bow+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Arch Bow+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Assisting Bow": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Assisting Bow+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Assisting Bow+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Assisting Bow+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Assisting Bow+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Assisting Bow+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Droid Sphere": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Droid Sphere+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Droid Sphere+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Droid Sphere+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Droid Sphere+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Droid Sphere+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Eclipse Sword": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Eclipse Sword+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Eclipse Sword+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Eclipse Sword+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Eclipse Sword+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Eclipse Sword+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fishing Pole": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Fishing Pole+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Fishing Pole+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Fishing Pole+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Fishing Pole+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fishing Pole+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Grim Ripper": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Grim Ripper+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Grim Ripper+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Grim Ripper+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Grim Ripper+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Grim Ripper+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Omni Sword": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Omni Sword+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Omni Sword+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Omni Sword+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Omni Sword+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Omni Sword+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "One Punch Fist": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "One Punch Fist+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "One Punch Fist+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "One Punch Fist+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "One Punch Fist+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "One Punch Fist+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Projectile Sphere": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Projectile Sphere+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Projectile Sphere+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Projectile Sphere+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Projectile Sphere+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Projectile Sphere+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Staff of Doom": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Staff of Doom+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Staff of Doom+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Staff of Doom+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Staff of Doom+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Staff of Doom+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Tiny Pin": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Tiny Pin+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Tiny Pin+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Tiny Pin+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Tiny Pin+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Tiny Pin+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),

    # Basic Accessories
    "Shell": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Shell+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Shell+2": ItemData(IC.filler, ["Equipment", "Tier 3", ]),
    "Shell+3": ItemData(IC.filler, ["Equipment", "Tier 4", ]),
    "Shell+4": ItemData(IC.filler, ["Equipment", "Tier 5", ]),
    "Shell+5": ItemData(IC.filler, ["Equipment", "Tier 5", ]),
    "Vital Ring": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Vital Ring+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Vital Ring+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Vital Ring+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Vital Ring+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Vital Ring+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Mana Ring": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Mana Ring+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Mana Ring+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Mana Ring+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Mana Ring+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Mana Ring+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Sustain Ring": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Sustain Ring+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Sustain Ring+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Sustain Ring+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Sustain Ring+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Sustain Ring+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Crit Ring": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Crit Ring+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Crit Ring+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Crit Ring+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Crit Ring+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Crit Ring+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Impact Ring": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Impact Ring+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Impact Ring+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Impact Ring+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Impact Ring+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Impact Ring+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Bandana": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Bandana+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Bandana+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Bandana+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Bandana+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Bandana+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Belt": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Belt+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Belt+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Belt+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Belt+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Belt+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Bracelet": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Bracelet+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Bracelet+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Bracelet+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Bracelet+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Bracelet+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Bracer": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Bracer+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Bracer+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Bracer+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Bracer+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Bracer+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Cape": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Cape+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Cape+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Cape+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Cape+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Cape+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Coat": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Coat+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Coat+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Coat+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Coat+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Coat+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Diadem": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Diadem+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Diadem+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Diadem+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Diadem+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Diadem+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Fang": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Fang+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Fang+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Fang+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Fang+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Fang+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Feather": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Feather+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Feather+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Feather+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Feather+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Feather+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Gauntlet": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Gauntlet+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Gauntlet+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Gauntlet+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Gauntlet+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Gauntlet+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Helmet": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Helmet+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Helmet+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Helmet+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Helmet+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Helmet+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Hide": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Hide+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Hide+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Hide+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Hide+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Hide+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Hood": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Hood+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Hood+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Hood+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Hood+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Hood+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Needle": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Needle+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Needle+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Needle+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Needle+ 4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Needle+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Ribbon": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Ribbon+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Ribbon+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Ribbon+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Ribbon+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Ribbon+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Scroll": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Scroll+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Scroll+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Scroll+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Scroll+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Scroll+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Tome": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Tome+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Tome+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Tome+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Tome+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Tome+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Wizard Hat": ItemData(IC.filler, ["Equipment", "Tier 1"]),
    "Wizard Hat+1": ItemData(IC.filler, ["Equipment", "Tier 2"]),
    "Wizard Hat+2": ItemData(IC.filler, ["Equipment", "Tier 3"]),
    "Wizard Hat+3": ItemData(IC.filler, ["Equipment", "Tier 4"]),
    "Wizard Hat+4": ItemData(IC.filler, ["Equipment", "Tier 5"]),
    "Wizard Hat+5": ItemData(IC.filler, ["Equipment", "Tier 5"]),

    # Unique Accessories
    "Ancestral Medal": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Ancestral Medal+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Ancestral Medal+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Ancestral Medal+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Ancestral Medal+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Ancestral Medal+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Bead Chain": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Bead Chain+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Bead Chain+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Bead Chain+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Bead Chain+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Bead Chain+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Blood Vessel": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Blood Vessel+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Blood Vessel+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Blood Vessel+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Blood Vessel+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Blood Vessel+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Brooch": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Brooch+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Brooch+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Brooch+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Brooch+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Brooch+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Buckler": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Buckler+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Buckler+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Buckler+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Buckler+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Buckler+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Cauldron": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Cauldron+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Cauldron+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Cauldron+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Cauldron+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Cauldron+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Charging Sphere": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Charging Sphere+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Charging Sphere+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Charging Sphere+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Charging Sphere+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Charging Sphere+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Crown": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Crown+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Crown+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Crown+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Crown+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Crown+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Drum": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Drum+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Drum+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Drum+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Drum+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Drum+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Dumbbell": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Dumbbell+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Dumbbell+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Dumbbell+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Dumbbell+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Dumbbell+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fin": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Fin+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Fin+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Fin+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Fin+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fin+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Flute": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Flute+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Flute+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Flute+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Flute+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Flute+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Frozen Tear": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Frozen Tear+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Frozen Tear+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Frozen Tear+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Frozen Tear+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Frozen Tear+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Gray Pearl": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Gray Pearl+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Gray Pearl+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Gray Pearl+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Gray Pearl+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Gray Pearl+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Hourglass": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Hourglass+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Hourglass+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Hourglass+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Hourglass+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Hourglass+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Infinity Flame": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Infinity Flame+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Infinity Flame+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Infinity Flame+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Infinity Flame+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Infinity Flame+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Lightning Sphere": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Lightning Sphere+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Lightning Sphere+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Lightning Sphere+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Lightning Sphere+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Lightning Sphere+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Lucky Clover": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Lucky Clover+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Lucky Clover+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Lucky Clover+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Lucky Clover+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Lucky Clover+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Mage Flask": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Mage Flask+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Mage Flask+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Mage Flask+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Mage Flask+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Mage Flask+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Medallion": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Medallion+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Medallion+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Medallion+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Medallion+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Medallion+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Ocarina": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Ocarina+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Ocarina+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Ocarina+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Ocarina+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Ocarina+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Omni Ring": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Omni Ring+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Omni Ring+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Omni Ring+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Omni Ring+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Omni Ring+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Ornate Pipe": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Ornate Pipe+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Ornate Pipe+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Ornate Pipe+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Ornate Pipe+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Ornate Pipe+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Pandora's Box": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Pandora's Box+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Pandora's Box+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Pandora's Box+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Pandora's Box+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Pandora's Box+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Poisoned Dart": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Poisoned Dart+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Poisoned Dart+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Poisoned Dart+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Poisoned Dart+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Poisoned Dart+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Shield Generator": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Shield Generator+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Shield Generator+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Shield Generator+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Shield Generator+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Shield Generator+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Slime Skin": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Slime Skin+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Slime Skin+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Slime Skin+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Slime Skin+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Slime Skin+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Spark": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Spark+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Spark+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Spark+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Spark+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Spark+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Sun Pendant": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Sun Pendant+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Sun Pendant+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Sun Pendant+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Sun Pendant+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Sun Pendant+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Tambourine": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Tambourine+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Tambourine+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Tambourine+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Tambourine+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Tambourine+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Tarot Card": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Tarot Card+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Tarot Card+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Tarot Card+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Tarot Card+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Tarot Card+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Thermal Reactor": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Thermal Reactor+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Thermal Reactor+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Thermal Reactor+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Thermal Reactor+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Thermal Reactor+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Totem": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Totem+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Totem+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Totem+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Totem+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Totem+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Warrior Flask": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Warrior Flask+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Warrior Flask+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Warrior Flask+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Warrior Flask+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Warrior Flask+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),

    # Relic Accessories
    "Ancient Clock": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Ancient Clock+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Ancient Clock+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Ancient Clock+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Ancient Clock+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Ancient Clock+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Cursed Drum": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Cursed Drum+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Cursed Drum+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Cursed Drum+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Cursed Drum+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Cursed Drum+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Devonian Medal": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Devonian Medal+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Devonian Medal+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Devonian Medal+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Devonian Medal+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Devonian Medal+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Dragon Saddle": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Dragon Saddle+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Dragon Saddle+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Dragon Saddle+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Dragon Saddle+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Dragon Saddle+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Dwarven Crown": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Dwarven Crown+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Dwarven Crown+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Dwarven Crown+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Dwarven Crown+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Dwarven Crown+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Earth Symbol": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Earth Symbol+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Earth Symbol+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Earth Symbol+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Earth Symbol+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Earth Symbol+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fire Symbol": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Fire Symbol+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Fire Symbol+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Fire Symbol+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Fire Symbol+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Fire Symbol+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Goblin Garment": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Goblin Garment+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Goblin Garment+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Goblin Garment+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Goblin Garment+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Goblin Garment+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Gold Feather": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Gold Feather+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Gold Feather+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Gold Feather+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Gold Feather+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Gold Feather+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Grey Stone": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Grey Stone+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Grey Stone+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Grey Stone+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Grey Stone+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Grey Stone+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Heavy Greaves": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Heavy Greaves+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Heavy Greaves+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Heavy Greaves+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Heavy Greaves+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Heavy Greaves+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Holy Necklace": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Holy Necklace+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Holy Necklace+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Holy Necklace+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Holy Necklace+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Holy Necklace+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Infinity Blaze": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Infinity Blaze+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Infinity Blaze+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Infinity Blaze+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Infinity Blaze+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Infinity Blaze+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Lion Fang": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Lion Fang+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Lion Fang+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Lion Fang+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Lion Fang+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Lion Fang+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Moon Ring": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Moon Ring+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Moon Ring+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Moon Ring+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Moon Ring+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Moon Ring+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Nimble Wings": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Nimble Wings+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Nimble Wings+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Nimble Wings+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Nimble Wings+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Nimble Wings+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Pandora's Chest": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Pandora's Chest+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Pandora's Chest+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Pandora's Chest+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Pandora's Chest+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Pandora's Chest+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Pure Leaf": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Pure Leaf+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Pure Leaf+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Pure Leaf+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Pure Leaf+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Pure Leaf+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Reptilian Idol": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Reptilian Idol+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Reptilian Idol+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Reptilian Idol+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Reptilian Idol+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Reptilian Idol+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Sharp Fin": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Sharp Fin+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Sharp Fin+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Sharp Fin+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Sharp Fin+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Sharp Fin+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Slimy Ball": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Slimy Ball+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Slimy Ball+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Slimy Ball+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Slimy Ball+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Slimy Ball+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Spirit Blaze": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Spirit Blaze+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Spirit Blaze+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Spirit Blaze+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Spirit Blaze+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Spirit Blaze+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Static Loop": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Static Loop+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Static Loop+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Static Loop+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Static Loop+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Static Loop+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Sun Ring": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Sun Ring+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Sun Ring+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Sun Ring+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Sun Ring+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Sun Ring+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Toxic Pot": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Toxic Pot+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Toxic Pot+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Toxic Pot+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Toxic Pot+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Toxic Pot+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Warlock Hat": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Warlock Hat+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Warlock Hat+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Warlock Hat+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Warlock Hat+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Warlock Hat+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Water Symbol": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Water Symbol+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Water Symbol+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Water Symbol+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Water Symbol+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Water Symbol+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Wind Symbol": ItemData(IC.filler, ["Equipment", "Tier 1", "Unique"]),
    "Wind Symbol+1": ItemData(IC.filler, ["Equipment", "Tier 2", "Unique"]),
    "Wind Symbol+2": ItemData(IC.filler, ["Equipment", "Tier 3", "Unique"]),
    "Wind Symbol+3": ItemData(IC.filler, ["Equipment", "Tier 4", "Unique"]),
    "Wind Symbol+4": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),
    "Wind Symbol+5": ItemData(IC.filler, ["Equipment", "Tier 5", "Unique"]),

    # Gold
    "100 G": ItemData(IC.filler, ["Currency", "Tier 1"]),
    "150 G": ItemData(IC.filler, ["Currency", "Tier 1"]),
    "200 G": ItemData(IC.filler, ["Currency", "Tier 1"]),
    "250 G": ItemData(IC.filler, ["Currency", "Tier 1"]),
    "300 G": ItemData(IC.filler, ["Currency", "Tier 2"]),
    "350 G": ItemData(IC.filler, ["Currency", "Tier 2"]),
    "400 G": ItemData(IC.filler, ["Currency", "Tier 2"]),
    "500 G": ItemData(IC.filler, ["Currency", "Tier 2"]),
    "600 G": ItemData(IC.filler, ["Currency", "Tier 3"]),
    "700 G": ItemData(IC.filler, ["Currency", "Tier 3"]),
    "800 G": ItemData(IC.filler, ["Currency", "Tier 3"]),
    "900 G": ItemData(IC.filler, ["Currency", "Tier 3"]),
    "1000 G": ItemData(IC.filler, ["Currency", "Tier 4"]),
    "1200 G": ItemData(IC.filler, ["Currency", "Tier 4"]),
    "1400 G": ItemData(IC.filler, ["Currency", "Tier 4"]),
    "1600 G": ItemData(IC.filler, ["Currency", "Tier 4"]),
    "1800 G": ItemData(IC.filler, ["Currency", "Tier 4"]),
    "2000 G": ItemData(IC.filler, ["Currency", "Tier 4"]),
    "2500 G": ItemData(IC.filler, ["Currency", "Tier 5"]),
    "3000 G": ItemData(IC.filler, ["Currency", "Tier 5"]),
    "3500 G": ItemData(IC.filler, ["Currency", "Tier 5"]),
    "4000 G": ItemData(IC.filler, ["Currency", "Tier 5"]),
    "4500 G": ItemData(IC.filler, ["Currency", "Tier 5"]),
    "5000 G": ItemData(IC.filler, ["Currency", "Tier 5"]),

    # Monsters
    # "Blob": ItemData(IC.progression, ["Monster", "Bubble Burst", "Water Orbs"]),
    # "Vaero": ItemData(IC.progression, ["Monster", "Flying", "Distant Ledges"]),
    # "Magmapillar": ItemData(IC.progression, ["Monster", "Ignite", "Impassible Vines", "Flame Orbs", "Torches"]),
    # "Spectral Wolf": ItemData(IC.progression, ["Monster", "Tackle", "Breakable Walls", "Impassible Vines"]),
    # "Rocky": ItemData(IC.progression, ["Monster", "Summon Rock", "Ground Switches"]),
    # "Catzerker": ItemData(IC.progression, ["Monster", "Slash", "Impassible Vines", "Breakable Walls"]),
    # "Spectral Toad": ItemData(IC.progression, ["Monster", "Tackle", "Breakable Walls", "Heavy Blocks"]),
    # "Spectral Eagle": ItemData(IC.progression, ["Monster", "Flying", "Distant Ledges"]),
    # "Spectral Lion": ItemData(IC.progression, ["Monster", "Claws", "Breakable Walls", "Impassible Vines"]),
    # "Yowie": ItemData(IC.progression, ["Monster", "Tackle", "Breakable Walls", "Heavy Blocks"]),
    # "Tanuki": ItemData(IC.progression, ["Monster", "Summon Mushroom", "Ground Switches"]),
    # "Manticorb": ItemData(IC.progression, ["Monster", "Light", "Dark Rooms"])
}

